import type { Module } from '../lib/types'

export const m1: Module = {
  id: 'm1',
  week: 'Week 1',
  title: 'Electronic Systems and Component Testing',
  tint: 'm1',
  teacherReviewed: false,
  competencies: [
    'Explain the overview of Electronic Systems Servicing.',
    'Discuss electronic components identification.',
    'Demonstrate procedures in testing electronic components.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Explain the overview of Electronic Systems Servicing',
      lessons: [{
        id: 'l1',
        title: 'What servicing actually involves',
        blocks: [
          { kind: 'text', md: 'Servicing an electronic product means restoring it to its working condition by finding the fault, correcting it, and proving the repair. Every device you will work on this term, from a rechargeable lamp to a CCTV recorder, is a system: a power source, a set of components that process a signal, and an output. When one part of that chain fails, the symptom you see is rarely at the point of failure.' },
          { kind: 'text', md: 'This is why servicing is a procedure and not a guess. You observe the symptom, form a theory about which stage of the system is at fault, test that stage, and only then replace anything.' },
          { kind: 'steps', items: [
            'Confirm the complaint. Operate the unit yourself and see the fault.',
            'Isolate the unit from the supply before opening it.',
            'Inspect visually for burning, swelling, corrosion, or broken joints.',
            'Divide the system into stages and test from the power source outward.',
            'Repair or replace the confirmed faulty part.',
            'Reassemble, then test the unit under normal operation before returning it.',
          ] },
          { kind: 'safety', md: 'Never open a mains-powered appliance while it is plugged in. Unplug it, then confirm with a meter that stored charge has drained before touching any internal part.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm1-lo1-q1', competency: 'Explain the overview of Electronic Systems Servicing.',
          stem: 'A customer reports that a desk fan does not turn on. What is the correct first action?',
          options: [
            'Replace the motor, since the motor drives the fan',
            'Operate the fan yourself to confirm the reported fault',
            'Open the housing immediately to inspect the windings',
            'Replace the power cord, since cords fail most often',
          ],
          answer: 1,
          rationale: [
            'Replacing a part before testing wastes it and does not prove the fault was there.',
            'Correct. Confirming the complaint tells you the real symptom before you commit to any theory.',
            'Opening the unit comes after confirming the fault and isolating the unit from the supply.',
            'Frequency of failure is a clue, not evidence. The cord still has to be tested.',
          ] },
        { kind: 'truefalse', id: 'm1-lo1-q2', competency: 'Explain the overview of Electronic Systems Servicing.',
          stem: 'The visible symptom of a fault is usually located at the component that failed.',
          answer: false,
          rationale: 'A failure in one stage often shows up as a symptom in a later stage. This is why you test stage by stage from the supply outward rather than replacing the part nearest the symptom.' },
        { kind: 'order', id: 'm1-lo1-q3', competency: 'Explain the overview of Electronic Systems Servicing.',
          stem: 'Arrange the servicing procedure in the correct order.',
          steps: [
            'Confirm the reported fault',
            'Isolate the unit from the supply',
            'Inspect visually for obvious damage',
            'Test stage by stage from the power source',
            'Repair or replace the faulty part',
            'Test the unit under normal operation',
          ] },
      ],
    },
    {
      id: 'lo2',
      title: 'Discuss electronic components identification',
      lessons: [{
        id: 'l1',
        title: 'Reading a component before you test it',
        blocks: [
          { kind: 'text', md: 'Components divide into two broad families. Passive components (resistors, capacitors, inductors) do not add energy to a signal. Active components (diodes, transistors, integrated circuits) control or amplify a signal and need a supply to work. Knowing which family a part belongs to tells you what a meter should read on it before you ever touch a probe to it.' },
          { kind: 'table',
            headers: ['Component', 'Family', 'Marking you read', 'What a healthy part shows'],
            rows: [
              ['Resistor', 'Passive', 'Colour bands', 'Its nominal value within tolerance'],
              ['Capacitor', 'Passive', 'Printed value and voltage', 'Charging behaviour, not a short'],
              ['Diode', 'Active', 'Body code and cathode band', 'Conducts one way only'],
              ['LED', 'Active', 'Package colour and lead length', 'Forward drop, lights on diode test'],
              ['Fuse', 'Passive', 'Current and voltage rating', 'Near zero ohms, continuity beeps'],
            ] },
          { kind: 'text', md: 'The four-band resistor code is the one marking you will read constantly. The first two bands are digits, the third is the number of zeros to add, and the fourth is tolerance. Gold in the fourth position means plus or minus five percent.' },
          { kind: 'interactive', simId: 'multimeter', config: { preset: 'identify' } },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm1-lo2-q1', competency: 'Discuss electronic components identification.',
          stem: 'A resistor is banded yellow, violet, red, gold. What is its value and tolerance?',
          options: ['470 ohms, 5 percent', '4.7 kilohms, 5 percent', '47 kilohms, 5 percent', '4.7 kilohms, 10 percent'],
          answer: 1,
          rationale: [
            'That would be yellow, violet, brown.',
            'Correct. Yellow is 4, violet is 7, red adds two zeros giving 4700 ohms, and gold is 5 percent.',
            'That would be yellow, violet, orange.',
            'Gold is 5 percent. Silver would be 10 percent.',
          ] },
        { kind: 'mcq', id: 'm1-lo2-q2', competency: 'Discuss electronic components identification.',
          stem: 'Which of these is an active component?',
          options: ['Carbon film resistor', 'Electrolytic capacitor', 'Signal diode', 'Wirewound inductor'],
          answer: 2,
          rationale: [
            'Resistors are passive. They dissipate energy, they do not control it.',
            'Capacitors are passive. They store and release energy without controlling a signal.',
            'Correct. A diode controls the direction of current flow, which makes it active.',
            'Inductors are passive.',
          ] },
        { kind: 'truefalse', id: 'm1-lo2-q3', competency: 'Discuss electronic components identification.',
          stem: 'A healthy fuse should read close to zero ohms on a meter.',
          answer: true,
          rationale: 'A fuse is a deliberate low-resistance link. Near zero ohms and a continuity beep mean it is intact. An open reading means it has blown.' },
      ],
    },
    {
      id: 'lo3',
      title: 'Demonstrate procedures in testing electronic components',
      lessons: [{
        id: 'l1',
        title: 'Using the multimeter on each component type',
        blocks: [
          { kind: 'text', md: 'A digital multimeter answers a different question in each mode. Choosing the wrong mode is the most common reason a good component appears faulty.' },
          { kind: 'table',
            headers: ['Mode', 'Question it answers', 'Use it on'],
            rows: [
              ['Ohms', 'How much does this resist current?', 'Resistors, heating elements, motor windings'],
              ['Continuity', 'Is there an unbroken path?', 'Fuses, switches, cables, connectors'],
              ['Diode test', 'Does this conduct one way only?', 'Diodes, LEDs, transistor junctions'],
              ['DC volts', 'What potential is present here?', 'Live circuits, batteries, supply rails'],
            ] },
          { kind: 'steps', items: [
            'Isolate the component from the supply and discharge any capacitors.',
            'Lift at least one leg of the component out of circuit where possible.',
            'Select the mode that matches the question you are asking.',
            'Touch the probes to the leads and let the reading settle.',
            'Compare the reading against the marked value and its tolerance.',
          ] },
          { kind: 'safety', md: 'A filter capacitor can hold a lethal charge long after the unit is unplugged. Discharge it through a bleeder resistor of about 2.2 kilohms rated 5 watts. Never short the terminals with a screwdriver: it welds the tip, damages the capacitor, and throws molten metal.' },
          { kind: 'note', md: 'Measuring a resistor while it is still soldered into a circuit usually reads low, because other parts in parallel with it also carry current. Lifting one leg removes those parallel paths.' },
          { kind: 'interactive', simId: 'multimeter', config: { preset: 'test' } },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm1-lo3-q1', competency: 'Demonstrate procedures in testing electronic components.',
          stem: 'A 4.7 kilohm resistor marked 5 percent measures 4.61 kilohms. What do you conclude?',
          options: [
            'It has drifted and should be replaced',
            'It is within tolerance and is good',
            'The meter is faulty',
            'It is shorted',
          ],
          answer: 1,
          rationale: [
            'Drift only matters once the reading falls outside the tolerance band.',
            'Correct. Five percent of 4.7 kilohms is 235 ohms, so anything from 4.465 to 4.935 kilohms is acceptable.',
            'The reading is consistent with a healthy part, so there is no reason to suspect the meter.',
            'A shorted resistor would read near zero ohms.',
          ] },
        { kind: 'mcq', id: 'm1-lo3-q2', competency: 'Demonstrate procedures in testing electronic components.',
          stem: 'Which mode confirms that a fuse is intact?',
          options: ['DC volts', 'Continuity', 'Diode test', 'AC volts'],
          answer: 1,
          rationale: [
            'DC volts measures potential, not whether a path is unbroken.',
            'Correct. Continuity tests for an unbroken low-resistance path, which is exactly what a fuse should provide.',
            'Diode test checks one-way conduction, which a fuse does not do.',
            'AC volts measures potential in an energised circuit.',
          ] },
        { kind: 'order', id: 'm1-lo3-q3', competency: 'Demonstrate procedures in testing electronic components.',
          stem: 'Arrange the steps to safely test a resistor in a mains appliance.',
          steps: [
            'Unplug the appliance from the supply',
            'Discharge the filter capacitor through a bleeder resistor',
            'Lift one leg of the resistor out of circuit',
            'Select the ohms mode on the meter',
            'Measure and compare against the marked value',
          ] },
      ],
    },
  ],
}
