import type { Module } from '../lib/types'

export const m2: Module = {
  id: 'm2',
  week: 'Week 2',
  title: 'PCB, Soldering and Power Supplies',
  tint: 'm2',
  teacherReviewed: false,
  competencies: [
    'Discuss the procedures for PCB designing, including design software and layout transfer techniques.',
    'Discuss soldering and desoldering.',
    'Discuss the different types of power supplies.',
    'Perform variable regulated power supply assembly.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Discuss the procedures for PCB designing',
      lessons: [{
        id: 'l1',
        title: 'From schematic to copper',
        blocks: [
          { kind: 'text', md: 'A printed circuit board turns a schematic into physical copper. The schematic says what connects to what. The layout says where each part sits and which path the copper takes between them. Those are two different problems, and confusing them is why a first board often works on paper and not on the bench.' },
          { kind: 'text', md: 'Design software such as KiCad or Fritzing keeps the two in step. You draw the schematic, assign a footprint to every component so the software knows its real size and pin spacing, then place and route on the board layer. The software checks that every connection in the schematic exists in copper.' },
          { kind: 'table',
            headers: ['Stage', 'What you decide', 'What goes wrong if you rush'],
            rows: [
              ['Schematic', 'What connects to what', 'A missing net that no amount of routing will fix'],
              ['Footprints', 'Real pad size and pin spacing', 'A part that will not physically fit its holes'],
              ['Placement', 'Where each part sits', 'Tracks that cannot reach without crossing'],
              ['Routing', 'The copper path between pads', 'Tracks too thin for the current they carry'],
              ['Transfer', 'Getting the artwork onto copper', 'Broken or bridged tracks before you even etch'],
            ] },
          { kind: 'text', md: 'Transfer is the step where a good design becomes a bad board. In toner transfer you print the layout mirrored onto glossy paper, iron it onto cleaned copper, and soak the paper away. In UV exposure you print onto transparent film and expose a photoresist-coated board through it. Both depend on the copper being clean: a fingerprint is enough to lift a track.' },
          { kind: 'safety', md: 'Etchant burns skin and eyes and ruins clothing. Wear gloves and eye protection, work where air moves, and never pour spent etchant down a drain: neutralise and dispose of it the way your school requires. Do not look into a UV exposure source, and treat the transfer iron as a soldering iron, because it is just as hot.' },
          { kind: 'steps', items: [
            'Print the layout at exactly 100 percent scale, mirrored for toner transfer.',
            'Clean the copper with fine abrasive and then with alcohol, and do not touch it again.',
            'Transfer the artwork by heat or by UV exposure, following the time your materials call for.',
            'Inspect every track under good light and repair breaks with a resist pen.',
            'Etch, then rinse thoroughly and remove the resist.',
            'Drill the holes, checking the bit against the largest lead you must fit.',
          ] },
          { kind: 'note', md: 'Track width carries current. A track that is fine for a signal will overheat on a power rail. Widen the tracks between the transformer, rectifier and filter capacitor before you route anything else.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm2-lo1-q1', competency: 'Discuss the procedures for PCB designing, including design software and layout transfer techniques.',
          stem: 'Your design software reports that a net in the schematic has no matching copper track. What does that mean?',
          options: [
            'Two pads that the schematic says are connected have no copper path between them',
            'The board is finished and the message can be ignored',
            'A track is too thin for its current',
            'A footprint is the wrong physical size',
          ],
          answer: 0,
          rationale: [
            'Correct. The schematic and the copper disagree, and the copper is what gets built.',
            'An unrouted net is a real gap. The board will not work as drawn.',
            'Track width is a separate check, usually reported as a design rule violation.',
            'A wrong footprint is a footprint error, not an unrouted net.',
          ] },
        { kind: 'mcq', id: 'm2-lo1-q2', competency: 'Discuss the procedures for PCB designing, including design software and layout transfer techniques.',
          stem: 'Why is the layout printed mirrored for toner transfer?',
          options: [
            'To save toner',
            'Because the etchant works from the back',
            'Because the printed side is pressed face down onto the copper',
            'To make the tracks thinner',
          ],
          answer: 2,
          rationale: [
            'Mirroring uses exactly the same amount of toner.',
            'Etchant removes exposed copper from the front. It has no direction.',
            'Correct. The artwork is flipped when it is pressed onto the board, so it must be printed reversed to come out the right way round.',
            'Mirroring does not change track width.',
          ] },
        { kind: 'order', id: 'm2-lo1-q3', competency: 'Discuss the procedures for PCB designing, including design software and layout transfer techniques.',
          stem: 'Arrange the board fabrication steps in the correct order.',
          steps: [
            'Print the layout at full scale',
            'Clean the copper surface',
            'Transfer the artwork onto the copper',
            'Inspect and repair broken tracks',
            'Etch away the exposed copper',
            'Drill the component holes',
          ] },
      ],
    },
    {
      id: 'lo2',
      title: 'Discuss soldering and desoldering',
      lessons: [{
        id: 'l1',
        title: 'Heat the joint, not the solder',
        blocks: [
          { kind: 'safety', md: 'A soldering iron tip runs between 300 and 400 degrees Celsius and gives no visual warning. Rest it in its stand every single time you put it down, work in ventilated air, and never flick molten solder off the tip.' },
          { kind: 'text', md: 'A good joint is made by heating the pad and the lead together and letting them melt the solder. If you melt solder on the tip and drop it onto a cold pad, it sits on top as a grey ball and conducts badly or not at all. That is a cold joint, and it is the single most common fault in student work.' },
          { kind: 'steps', items: [
            'Tin the tip with a little fresh solder and wipe it on a damp sponge or brass wool.',
            'Press the tip so it touches both the pad and the component lead at once.',
            'Count about two seconds, then feed solder into the joint, not onto the tip.',
            'Remove the solder first, then the iron, and let the joint cool without moving it.',
            'Look at the result: a good joint is shiny and slopes smoothly from pad to lead.',
          ] },
          { kind: 'table',
            headers: ['What you see', 'What it means', 'What to do'],
            rows: [
              ['Shiny, concave, wets the pad', 'A sound joint', 'Nothing'],
              ['Dull grey ball sitting on the pad', 'Cold joint, the pad was never hot enough', 'Reheat with the iron on the pad and lead together'],
              ['Solder bridging two adjacent pads', 'Too much solder, or the tip dragged', 'Remove with braid, then re-solder one pad'],
              ['Pad lifted from the board', 'Too much heat for too long', 'Repair with a wire link to the next point on the net'],
              ['Cracked ring around the lead', 'The joint moved while cooling', 'Reheat and let it cool untouched'],
            ] },
          { kind: 'text', md: 'Desoldering runs the same rules backwards. Heat the joint until the solder is fully liquid, then remove it in one action with a pump or with braid. Braid works by capillary action, so it must be pressed flat against the molten joint by the tip. Repeated half-hearted attempts cook the pad and lift it.' },
          { kind: 'note', md: 'Flux is not optional. It cleans the oxide off the metal at soldering temperature so the solder can wet it. Most solder wire has flux in its core, but an old joint you are reworking usually needs more.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm2-lo2-q1', competency: 'Discuss soldering and desoldering.',
          stem: 'A joint is a dull grey ball sitting on top of the pad. What happened?',
          options: [
            'The solder was melted on the iron and dropped onto a cold pad',
            'Too much flux was used',
            'The iron was too hot',
            'The lead was too thin for the hole',
          ],
          answer: 0,
          rationale: [
            'Correct. That is a cold joint. The pad never reached soldering temperature, so the solder never wet it.',
            'Excess flux leaves a sticky residue, not a grey ball.',
            'An over-hot iron tends to lift pads or burn flux, and the joint still wets.',
            'A loose lead makes a mechanically weak joint, but the solder still flows onto a hot pad.',
          ] },
        { kind: 'truefalse', id: 'm2-lo2-q2', competency: 'Discuss soldering and desoldering.',
          stem: 'When desoldering with braid, the braid should be pressed flat against the joint by the iron tip.',
          answer: true,
          rationale: 'Braid lifts solder by capillary action, which only works when the braid, the molten solder and the heat are all in contact at once. Holding the braid above the joint just wastes it.' },
        { kind: 'order', id: 'm2-lo2-q3', competency: 'Discuss soldering and desoldering.',
          stem: 'Arrange the steps for making a sound solder joint.',
          steps: [
            'Tin and wipe the iron tip',
            'Touch the tip to the pad and the lead together',
            'Feed solder into the joint',
            'Remove the solder, then the iron',
            'Let the joint cool without moving it',
          ] },
      ],
    },
    {
      id: 'lo3',
      title: 'Discuss the different types of power supplies',
      lessons: [{
        id: 'l1',
        title: 'What each kind of supply is for',
        blocks: [
          { kind: 'text', md: 'Every supply does the same job: take the power that is available and deliver the power a circuit needs. They differ in how they do it, and each way of doing it costs something.' },
          { kind: 'table',
            headers: ['Type', 'How it works', 'Strength', 'Cost'],
            rows: [
              ['Unregulated linear', 'Transformer, rectifier, filter capacitor', 'Simple, cheap, quiet', 'Output sags as the load rises'],
              ['Regulated linear', 'Adds a regulator after the filter', 'Steady output, very low noise', 'Wastes the surplus as heat'],
              ['Switching', 'Chops the input at high frequency', 'Small, light, efficient', 'Electrical noise, more parts to fail'],
              ['Battery', 'Stored chemical energy', 'Portable, no mains hazard', 'Voltage falls as it discharges'],
            ] },
          { kind: 'text', md: 'A linear regulator holds its output steady by dropping whatever is left over across itself. That surplus becomes heat, which is why a 12 volt regulator fed from 20 volts at half an amp needs a heatsink. A switching supply avoids that waste by chopping and only delivering the energy needed, but the chopping puts noise on the output that sensitive audio and radio circuits will pick up.' },
          { kind: 'note', md: 'The reason a regulated supply matters for servicing is that it lets you feed a repaired board a known, clean voltage. A sagging or noisy bench supply will make a working board look faulty.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm2-lo3-q1', competency: 'Discuss the different types of power supplies.',
          stem: 'Why does a linear regulator need a heatsink when the input voltage is much higher than the output?',
          options: [
            'Because it switches at high frequency',
            'Because the transformer conducts heat into it',
            'Because the filter capacitor warms it',
            'Because it dissipates the surplus voltage as heat',
          ],
          answer: 3,
          rationale: [
            'Switching is what a switching supply does. A linear regulator does not switch.',
            'Transformer heat is a separate and much smaller effect.',
            'The capacitor stores charge. It is not the heat source here.',
            'Correct. The regulator drops the difference between input and output, and that dropped voltage times the current is heat it must shed.',
          ] },
        { kind: 'mcq', id: 'm2-lo3-q2', competency: 'Discuss the different types of power supplies.',
          stem: 'Which supply would you avoid for a sensitive audio preamplifier, and why?',
          options: [
            'Regulated linear, because it wastes power',
            'Unregulated linear, because it uses a transformer',
            'Battery, because it is portable',
            'Switching, because its chopping puts noise on the output',
          ],
          answer: 3,
          rationale: [
            'Wasted power is an efficiency problem, not an audio problem.',
            'A transformer is not itself a noise source of concern here.',
            'Batteries are among the quietest supplies available.',
            'Correct. The high frequency switching couples noise onto the rail, and an audio stage will amplify it.',
          ] },
        { kind: 'truefalse', id: 'm2-lo3-q3', competency: 'Discuss the different types of power supplies.',
          stem: 'An unregulated linear supply holds its output voltage steady as the load current increases.',
          answer: false,
          rationale: 'It does not. With no regulator, the output falls as the load draws more current and the filter capacitor discharges further between peaks. Holding the voltage steady is exactly what the regulator adds.' },
      ],
    },
    {
      id: 'lo4',
      title: 'Perform variable regulated power supply assembly',
      lessons: [{
        id: 'l1',
        title: 'Building a supply that holds its voltage',
        blocks: [
          { kind: 'safety', md: 'The transformer primary side carries mains voltage. Wire and insulate the primary completely before the board goes anywhere near an outlet, and never work on the primary side with the unit plugged in.' },
          { kind: 'text', md: 'A regulated supply is four stages in a line. The transformer steps the mains down. The rectifier turns alternating current into one-directional pulses. The filter capacitor fills the gaps between those pulses. The regulator shaves whatever is left down to a flat, exact voltage.' },
          { kind: 'text', md: 'The stage that students get wrong is the filter. A capacitor that is too small lets the voltage fall a long way between pulses, and if it falls to within about two volts of the target the regulator runs out of headroom and the output sags with it. The simulator below lets you see that happen and fix it.' },
          { kind: 'interactive', simId: 'psu', config: { preset: 'assembly' } },
          { kind: 'steps', items: [
            'Lay the components out on the board in the order the signal flows through them.',
            'Mount and solder the transformer and the rectifier first, keeping the power tracks short.',
            'Fit the filter capacitor, observing polarity. The negative stripe goes to the negative rail.',
            'Fit the regulator on its heatsink, checking the pinout against its datasheet.',
            'Inspect every joint before applying power for the first time.',
            'Power up with no load and confirm the output voltage, then repeat under load.',
          ] },
          { kind: 'note', md: 'An electrolytic filter capacitor fitted backwards will heat, vent and sometimes burst. Check the stripe twice. It is the one polarity mistake in this build that is both easy to make and loud.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm2-lo4-q1', competency: 'Perform variable regulated power supply assembly.',
          stem: 'Your 12 volt regulated output is steady with no load but drops to 10.5 volts and hums under a 500 mA load. What is the most likely cause?',
          options: [
            'The filter capacitor is too small for the load, so the ripple trough falls below the regulator dropout',
            'The regulator is faulty and must be replaced',
            'The transformer secondary voltage is too high',
            'The rectifier diodes are fitted backwards',
          ],
          answer: 0,
          rationale: [
            'Correct. Under load the capacitor discharges further between peaks, and once the trough is within about two volts of 12 the regulator cannot hold.',
            'A faulty regulator usually fails to a fixed wrong value or to nothing, not to a load-dependent hum.',
            'Too high a secondary makes the regulator run hot, but the output would still hold at 12.',
            'Reversed diodes would give no useful output at all, loaded or not.',
          ] },
        { kind: 'mcq', id: 'm2-lo4-q2', competency: 'Perform variable regulated power supply assembly.',
          stem: 'A full wave bridge rectifier charges the filter capacitor twice per mains cycle rather than once. What does that buy you?',
          options: [
            'Less ripple for the same capacitor and load',
            'A higher peak voltage',
            'Fewer components',
            'A lower transformer temperature',
          ],
          answer: 0,
          rationale: [
            'Correct. The capacitor is topped up twice as often, so it has half as long to droop between peaks.',
            'The peak is actually slightly lower, because the current passes through two diodes instead of one.',
            'A bridge uses four diodes rather than one, so it is more components, not fewer.',
            'Transformer temperature is set by the load, not by the rectifier arrangement.',
          ] },
        { kind: 'order', id: 'm2-lo4-q3', competency: 'Perform variable regulated power supply assembly.',
          stem: 'Arrange the assembly steps for a regulated DC supply.',
          steps: [
            'Plan the component layout following the signal path',
            'Mount and solder the transformer and rectifier',
            'Fit the filter capacitor, observing polarity',
            'Fit the regulator on its heatsink',
            'Inspect every joint before applying power',
            'Test the output with no load, then under load',
          ] },
      ],
    },
  ],
}
