import type { Module } from '../lib/types'

export const m3: Module = {
  id: 'm3',
  week: 'Week 3',
  title: 'Appliances with Electric Motors',
  tint: 'm3',
  teacherReviewed: false,
  competencies: [
    'Discuss the procedures in servicing appliances with electric motors.',
    'Apply procedures in servicing appliances with electric motors.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Discuss the procedures in servicing appliances with electric motors',
      lessons: [{
        id: 'l1',
        title: 'What is inside a small appliance motor',
        blocks: [
          { kind: 'safety', md: 'Unplug the appliance before opening it, every time, with no exception for a quick look. A fan or blender that appears dead can still hold charge in its run capacitor, and a motor that starts unexpectedly while your hand is near the blades causes serious injury.' },
          { kind: 'text', md: 'Most household appliances use one of two motor types. A shaded pole motor, found in fans and small blowers, is cheap, quiet and has no brushes to wear out. A universal motor, found in blenders and drills, is more powerful for its size and uses carbon brushes that press against a rotating commutator. Brushes wear out, so a universal motor is a serviceable motor.' },
          { kind: 'table',
            headers: ['Part', 'What it does', 'How it usually fails'],
            rows: [
              ['Stator winding', 'Creates the rotating magnetic field', 'Opens from overheating, or shorts turn to turn'],
              ['Rotor', 'Turns inside the field and drives the shaft', 'Rarely fails, but the shaft can seize'],
              ['Bearings or bushes', 'Let the shaft turn freely', 'Dry out, then run hot and noisy'],
              ['Run capacitor', 'Shifts the phase so the motor starts and runs', 'Loses capacitance, so the motor hums but will not start'],
              ['Thermal fuse', 'Cuts power if the winding overheats', 'Opens permanently once it has done its job'],
              ['Carbon brushes', 'Carry current to the spinning commutator', 'Wear down until they no longer touch'],
            ] },
          { kind: 'text', md: 'The thermal fuse is worth understanding properly, because it is the part most often blamed and most often misunderstood. It is a one-shot device buried in the windings. When the winding gets too hot it opens and never closes again. An open thermal fuse is usually a symptom rather than the disease: something made the motor run hot, and if you fit a new fuse without finding out what, the new one will open too.' },
          { kind: 'note', md: 'Never bridge a thermal fuse to get an appliance working. It is the only thing standing between an overheating winding and a fire, and bridging it moves the failure from an inconvenience to a house fire.' },
          { kind: 'steps', items: [
            'Unplug the appliance and let any capacitor discharge.',
            'Open the housing and photograph the wiring before disturbing it.',
            'Turn the shaft by hand and feel for roughness, tightness or play.',
            'Inspect for burnt smell, discoloured windings and dried out bearings.',
            'Test electrically from the plug inward: cord, switch, thermal fuse, capacitor, winding.',
            'Clean, lubricate and reassemble, then run the appliance and watch it under load.',
          ] },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm3-lo1-q1', competency: 'Discuss the procedures in servicing appliances with electric motors.',
          stem: 'An electric fan hums but the blades do not turn, and they spin freely by hand. What is the most likely cause?',
          options: [
            'An open thermal fuse',
            'A failed run capacitor',
            'A broken supply cord',
            'Worn carbon brushes',
          ],
          answer: 1,
          rationale: [
            'An open thermal fuse cuts the circuit completely, so there would be no hum at all.',
            'Correct. The hum means current is reaching the winding, but without the capacitor there is no phase shift to start rotation.',
            'A broken cord would give no hum, because no current would reach the motor.',
            'A shaded pole fan motor has no brushes.',
          ] },
        { kind: 'truefalse', id: 'm3-lo1-q2', competency: 'Discuss the procedures in servicing appliances with electric motors.',
          stem: 'If a thermal fuse has opened, fitting a new one is a complete repair.',
          answer: false,
          rationale: 'It is not. The fuse opened because something made the winding overheat: a dry bearing, a blocked airflow, or a failing capacitor. Fit a new fuse without finding that cause and the new fuse will open too.' },
        { kind: 'order', id: 'm3-lo1-q3', competency: 'Discuss the procedures in servicing appliances with electric motors.',
          stem: 'Arrange the steps for servicing a motor-driven appliance.',
          steps: [
            'Unplug the appliance and let any capacitor discharge',
            'Open the housing and photograph the wiring',
            'Turn the shaft by hand and feel for roughness',
            'Inspect for burnt smell and discoloured windings',
            'Test electrically from the plug inward',
            'Clean, lubricate, reassemble and run under load',
          ] },
      ],
    },
    {
      id: 'lo2',
      title: 'Apply procedures in servicing appliances with electric motors',
      lessons: [{
        id: 'l1',
        title: 'Working from the plug inward',
        blocks: [
          { kind: 'text', md: 'Testing in a fixed order matters more than testing cleverly. Start at the plug and work toward the motor, and each test you pass rules out everything behind it. Jumping straight to the winding tells you nothing useful if the cord is broken, because you would find a healthy winding on an appliance that still does not work.' },
          { kind: 'text', md: 'For a dead unit that you have unplugged and isolated, almost every test is a continuity or resistance test. You are asking one question over and over: is there an unbroken path here? Only when you find the place where the path stops have you found the fault.' },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'fan' } },
          { kind: 'table',
            headers: ['Test point', 'A healthy reading', 'What a bad reading means'],
            rows: [
              ['Plug pins, switch on', 'Under an ohm, meter beeps', 'Open cord, or the switch is not making'],
              ['Switch contacts, each speed', 'Beeps on every speed', 'Worn or dirty contacts'],
              ['Thermal fuse', 'Under an ohm, meter beeps', 'Fuse has opened, and something made it open'],
              ['Run capacitor', 'Close to its marked value', 'Lost capacitance, motor will hum but not start'],
              ['Main winding', 'Tens to hundreds of ohms', 'Open winding, usually the end of the motor'],
            ] },
          { kind: 'safety', md: 'Discharge the run capacitor through a resistor before you put a meter or a finger on its terminals. A capacitor in a fan can hold enough charge to hurt you long after the fan is unplugged, and shorting it with a screwdriver damages both the capacitor and the screwdriver.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm3-lo2-q1', competency: 'Apply procedures in servicing appliances with electric motors.',
          stem: 'Why test from the plug inward rather than starting at the motor winding?',
          options: [
            'The winding is harder to reach',
            'Each test you pass rules out everything behind it',
            'The winding test needs mains power',
            'It is the order the manufacturer prints in the manual',
          ],
          answer: 1,
          rationale: [
            'Access is a convenience, not the reason for the order.',
            'Correct. Working outward in means every healthy reading narrows the search, and you never mistake a healthy winding for a working appliance.',
            'A winding test is a resistance test on an isolated unit. It needs no mains power.',
            'Manuals vary. The reasoning holds whether or not one is available.',
          ] },
        { kind: 'mcq', id: 'm3-lo2-q2', competency: 'Apply procedures in servicing appliances with electric motors.',
          stem: 'Your meter reads OL across the thermal fuse of a dead fan. What is the correct conclusion?',
          options: [
            'The fuse is fine, since OL means no resistance',
            'The fuse has opened, and you should also find out what made it overheat',
            'The winding is open',
            'The capacitor has failed',
          ],
          answer: 1,
          rationale: [
            'OL means an open circuit, the opposite of no resistance. A healthy fuse reads close to zero ohms.',
            'Correct. The fuse has done its job, and the job implies the winding got too hot for a reason you have not found yet.',
            'The winding is tested separately, and this reading says nothing about it.',
            'A failed capacitor gives a hum, not a completely dead unit.',
          ] },
        { kind: 'truefalse', id: 'm3-lo2-q3', competency: 'Apply procedures in servicing appliances with electric motors.',
          stem: 'A run capacitor should be discharged before you measure it.',
          answer: true,
          rationale: 'Yes. A charged capacitor can injure you and can damage a meter set to measure capacitance. Discharge it through a resistor, never by shorting it with a screwdriver.' },
      ],
    },
  ],
}
