import type { Module } from '../lib/types'

export const m4: Module = {
  id: 'm4',
  week: 'Week 4 to 5',
  title: 'Heating Appliances and Lighting Units',
  tint: 'm4',
  teacherReviewed: false,
  competencies: [
    'Discuss the procedures in servicing appliances with heating components.',
    'Apply procedure in servicing appliances with heating components.',
    'Discuss the procedures in servicing rechargeable and electronic-controlled lighting units.',
    'Demonstrate the procedure in servicing electronic controlled lighting units.',
    'Discuss the principles of Closed-Circuit Television (CCTV) system.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Discuss the procedures in servicing appliances with heating components',
      lessons: [{
        id: 'l1',
        title: 'How a heating appliance protects itself',
        blocks: [
          { kind: 'safety', md: 'A heating appliance stays dangerously hot long after it is switched off, and a flat iron plate can burn you minutes after the power is gone. Unplug it, let it cool to the touch, and only then open it.' },
          { kind: 'text', md: 'A heating appliance turns electricity into heat on purpose, which means every one of them is built around the problem of stopping. An iron, a rice cooker, a toaster and a water heater all share the same chain: something makes the heat, something decides how much, and something cuts the power when the deciding fails.' },
          { kind: 'table',
            headers: ['Part', 'Its job', 'How it fails'],
            rows: [
              ['Heating element', 'Turns current into heat', 'Opens, usually where it enters the terminal'],
              ['Thermostat', 'Switches the element on and off to hold a setting', 'Contacts pit and stick, or stop closing at all'],
              ['Thermal fuse', 'Cuts power permanently if the appliance overheats', 'Opens once, and never closes again'],
              ['Indicator lamp', 'Shows the element is being fed', 'Fails open, which looks like a dead appliance'],
              ['Supply cord', 'Carries the current in', 'Breaks inside the sleeve near the strain relief'],
            ] },
          { kind: 'text', md: 'The thermostat and the thermal fuse are often confused, and telling them apart is most of this outcome. A thermostat is a switch that is meant to open and close thousands of times. A thermal fuse is meant to open exactly once, in an emergency, and then be replaced. If an appliance works again after cooling down, suspect the thermostat. If it never works again, suspect the fuse.' },
          { kind: 'interactive', simId: 'hotspot', config: { activity: 'flat-iron-parts' } },
          { kind: 'note', md: 'An element measured cold reads its full resistance. A 1000 watt element on 230 volts reads about 53 ohms. If you measure a few ohms, you are probably reading across the wrong pair of terminals.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm4-lo1-q1', competency: 'Discuss the procedures in servicing appliances with heating components.',
          stem: 'A rice cooker works for a while, then stops, then works again after an hour of cooling. Which part is most likely at fault?',
          options: [
            'The thermal fuse',
            'The thermostat',
            'The supply cord',
            'The heating element',
          ],
          answer: 1,
          rationale: [
            'A thermal fuse opens once and never closes again, so the appliance would not come back on its own.',
            'Correct. A thermostat that opens too early and resets on cooling produces exactly this pattern.',
            'A broken cord gives no power at all, and would not repair itself as the unit cools.',
            'An open element does not heal on cooling.',
          ] },
        { kind: 'truefalse', id: 'm4-lo1-q2', competency: 'Discuss the procedures in servicing appliances with heating components.',
          stem: 'A thermal fuse that has opened can be reset once the appliance has cooled.',
          answer: false,
          rationale: 'It cannot. A thermal fuse is a one-shot device. It opens once and must be replaced with one of the same current rating and the same temperature rating.' },
        { kind: 'mcq', id: 'm4-lo1-q3', competency: 'Discuss the procedures in servicing appliances with heating components.',
          stem: 'You measure 53 ohms across the element of a 1000 watt iron. What does that tell you?',
          options: [
            'The element is shorted',
            'The element is open',
            'The element is intact',
            'The thermostat is stuck closed',
          ],
          answer: 2,
          rationale: [
            'A shorted element would read close to zero ohms.',
            'An open element reads OL, not a sensible resistance.',
            'Correct. That is about what a 1000 watt element on 230 volts should read cold, so the element itself is fine and the fault is elsewhere.',
            'This measurement says nothing about the thermostat. Test it separately.',
          ] },
      ],
    },
    {
      id: 'lo2',
      title: 'Apply procedure in servicing appliances with heating components',
      lessons: [{
        id: 'l1',
        title: 'Finding the break in a cold iron',
        blocks: [
          { kind: 'text', md: 'The sweep for a heating appliance is the same one you learned on the fan: start at the plug and work inward, and each healthy reading rules out everything behind it. For an iron the order is cord, thermostat, thermal fuse, element.' },
          { kind: 'steps', items: [
            'Unplug the iron and let the plate cool completely.',
            'Check the cord for continuity, flexing it along its length as you measure.',
            'Check the thermostat contacts with the dial turned to maximum.',
            'Check the thermal fuse, which usually sits under the cover near the element terminals.',
            'Measure the element itself across the sole plate terminals.',
            'Replace only the part that failed, then run the iron and watch it cycle at least twice.',
          ] },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'flat-iron' } },
          { kind: 'safety', md: 'Never bridge a thermal fuse to prove a diagnosis, not even for a moment. The fuse is the only protection against a runaway element in an appliance that a user leaves face down on a board.' },
          { kind: 'note', md: 'Flexing the cord while you measure is the step most people skip. A cord that reads fine at rest can open when it is bent the way it bends in use, and that intermittent fault will come back to you a week later.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm4-lo2-q1', competency: 'Apply procedure in servicing appliances with heating components.',
          stem: 'Your continuity test on an iron reads OL across the element but the cord, thermostat and thermal fuse all pass. What do you conclude?',
          options: [
            'The thermal fuse must be retested',
            'The element is open and the sole plate assembly needs replacing',
            'The iron is safe to return',
            'The thermostat is stuck open',
          ],
          answer: 1,
          rationale: [
            'The fuse already passed. Retesting a passing part before acting on a failing one is wasted work.',
            'Correct. Everything ahead of the element passes and the element does not, so the break is in the element.',
            'An iron that will not heat is not a repaired iron.',
            'The thermostat passed its own test.',
          ] },
        { kind: 'truefalse', id: 'm4-lo2-q2', competency: 'Apply procedure in servicing appliances with heating components.',
          stem: 'A supply cord should be flexed along its length while its continuity is measured.',
          answer: true,
          rationale: 'Yes. Cords break inside the insulation from flexing, most often near the plug or the strain relief, and a break can close again at rest. Flexing while measuring is what exposes an intermittent one.' },
        { kind: 'order', id: 'm4-lo2-q3', competency: 'Apply procedure in servicing appliances with heating components.',
          stem: 'Arrange the steps for finding why a flat iron will not heat.',
          steps: [
            'Unplug the iron and let the plate cool',
            'Test the supply cord, flexing it as you measure',
            'Test the thermostat contacts at maximum',
            'Test the thermal fuse',
            'Measure the heating element',
            'Replace the failed part and watch the iron cycle twice',
          ] },
      ],
    },
    {
      id: 'lo3',
      title: 'Discuss the procedures in servicing rechargeable and electronic-controlled lighting units',
      lessons: [{
        id: 'l1',
        title: 'What is inside a rechargeable lamp',
        blocks: [
          { kind: 'text', md: 'A rechargeable lamp is four blocks in a line. A charging circuit takes power from an adaptor and puts it into a cell at a rate the cell can accept. The cell stores it. A driver takes whatever the cell currently holds and pushes a steady current through the LEDs. The LEDs turn that current into light.' },
          { kind: 'text', md: 'Knowing that chain tells you what a symptom means. A lamp that runs briefly has a storage problem. A lamp that never charges has a problem before the cell. A lamp that lights unevenly or flickers has a driver or LED problem, because the cell cannot make light on its own.' },
          { kind: 'interactive', simId: 'match', config: { activity: 'lighting-parts' } },
          { kind: 'safety', md: 'A lithium cell cannot be switched off. Treat it as live whenever the case is open, never puncture or bend it, and never solder directly onto the cell body, because the heat can make it vent or catch fire. Fit replacements with their protection circuit intact.' },
          { kind: 'note', md: 'A cell that reads its normal voltage with nothing connected can still be worn out. Capacity shows up only under load, which is why a cell is judged by what its voltage does when the lamp is switched on, not by what it reads at rest.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm4-lo3-q1', competency: 'Discuss the procedures in servicing rechargeable and electronic-controlled lighting units.',
          stem: 'A rechargeable lamp lights normally but runs for only three minutes. Which block is at fault?',
          options: [
            'The LED array',
            'The cell',
            'The driver',
            'The control switch',
          ],
          answer: 1,
          rationale: [
            'The LEDs light normally, so they are receiving current and working.',
            'Correct. Normal brightness for a short time is a storage problem, which is the cell.',
            'A failing driver shows up as flicker or wrong brightness, not as a short run at the right brightness.',
            'A switch either passes current or does not. It does not limit how long the lamp runs.',
          ] },
        { kind: 'truefalse', id: 'm4-lo3-q2', competency: 'Discuss the procedures in servicing rechargeable and electronic-controlled lighting units.',
          stem: 'A cell that reads its rated voltage at rest is proven good.',
          answer: false,
          rationale: 'It is not. A worn cell can sit at its rated voltage with nothing drawing from it and then collapse the moment the lamp is switched on. Capacity is only visible under load.' },
        { kind: 'mcq', id: 'm4-lo3-q3', competency: 'Discuss the procedures in servicing rechargeable and electronic-controlled lighting units.',
          stem: 'Why should a replacement lithium cell keep its protection circuit?',
          options: [
            'It makes the lamp brighter',
            'It prevents over-charge, over-discharge and short circuit, any of which can make the cell vent or burn',
            'It is required for the charging indicator to work',
            'It increases the capacity of the cell',
          ],
          answer: 1,
          rationale: [
            'Protection has no effect on brightness.',
            'Correct. The protection board is the cell safety device, and a lamp is left charging unattended in a home.',
            'The indicator is driven by the charging circuit, not by the cell protection.',
            'Protection does not change capacity.',
          ] },
      ],
    },
    {
      id: 'lo4',
      title: 'Demonstrate the procedure in servicing electronic controlled lighting units',
      lessons: [{
        id: 'l1',
        title: 'Working through a lamp that will not charge',
        blocks: [
          { kind: 'text', md: 'The sweep runs the same direction as always, from the supply toward the load. For a lamp that is adaptor, jack, charging circuit, cell, then LEDs. Most lamps that reach a bench have one of the first two faults, because the jack takes mechanical stress every time someone plugs it in.' },
          { kind: 'steps', items: [
            'Unplug the charger and switch the lamp off before opening the case.',
            'Measure the adaptor output on its own, with nothing connected.',
            'Measure at the jack solder pads while wiggling the plug, watching for a reading that flickers.',
            'Measure the charging circuit output while the lamp is on charge.',
            'Measure the cell after ten minutes on charge, then again with the lamp switched on.',
            'Reassemble, charge fully, and run the lamp until it cuts off to confirm the runtime.',
          ] },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'lamp' } },
          { kind: 'note', md: 'The last step is the one that gets skipped and the one that matters most to the owner. A lamp that charges is not a repaired lamp; a lamp that charges and then runs for its rated time is.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm4-lo4-q1', competency: 'Demonstrate the procedure in servicing electronic controlled lighting units.',
          stem: 'At the charging jack you read 5.0 volts, but it drops out and returns as you wiggle the plug. What is the fault?',
          options: [
            'The adaptor is failing under load',
            'The jack solder joints are cracked',
            'The cell is worn',
            'The charging circuit has failed',
          ],
          answer: 1,
          rationale: [
            'The adaptor is upstream of the jack and its output was already measured on its own.',
            'Correct. A reading that changes with mechanical movement is a mechanical fault, and the jack is where the plugging stress lands.',
            'A worn cell affects runtime, not whether voltage reaches the jack.',
            'The charging circuit sits after the jack, so it cannot cause an intermittent reading at the jack itself.',
          ] },
        { kind: 'truefalse', id: 'm4-lo4-q2', competency: 'Demonstrate the procedure in servicing electronic controlled lighting units.',
          stem: 'A lamp that charges again after repair can be returned without running it down.',
          answer: false,
          rationale: 'No. Charging proves the input side works. Only running the lamp until it cuts off proves the cell actually holds the capacity the owner is paying for.' },
        { kind: 'order', id: 'm4-lo4-q3', competency: 'Demonstrate the procedure in servicing electronic controlled lighting units.',
          stem: 'Arrange the steps for servicing a rechargeable lamp that will not charge.',
          steps: [
            'Unplug the charger and switch the lamp off',
            'Measure the adaptor output on its own',
            'Measure at the jack while wiggling the plug',
            'Measure the charging circuit output on charge',
            'Measure the cell on charge and then under load',
            'Reassemble, charge fully and confirm the runtime',
          ] },
      ],
    },
    {
      id: 'lo5',
      title: 'Discuss the principles of Closed-Circuit Television (CCTV) system',
      lessons: [{
        id: 'l1',
        title: 'What a CCTV system is made of',
        blocks: [
          { kind: 'text', md: 'A CCTV system is a closed loop: cameras capture, cable carries, a recorder stores, and a monitor displays. Closed circuit means the picture goes only to that loop, which is what separates it from broadcast television and is where the name comes from.' },
          { kind: 'table',
            headers: ['Part', 'Its job', 'What goes wrong'],
            rows: [
              ['Camera', 'Captures the image and sends it down the cable', 'Lens fogs or dirties, infrared array fails at night'],
              ['Cable', 'Carries video and often power', 'Connector corrodes, or the run is too long for the signal'],
              ['Power supply', 'Feeds every camera', 'Sags when too many cameras share one supply'],
              ['Recorder', 'Stores footage and serves it to a monitor', 'Disk fills or fails, so nothing is retained'],
              ['Monitor', 'Displays live and recorded video', 'Wrong input selected, which looks like a dead system'],
            ] },
          { kind: 'text', md: 'Two ideas decide how a system is designed. Coverage is what the cameras can actually see, which depends on where they are mounted and how wide the lens is, and a camera pointed at a bright window will show you a silhouette and nothing else. Retention is how many days of footage the recorder holds before it overwrites, which depends on disk size, how many cameras there are and what quality they record at.' },
          { kind: 'note', md: 'Most CCTV complaints are not faults. A system that has quietly been overwriting after two days, or a camera that has drifted to point at a wall, will be reported as broken only when someone finally needs the footage.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm4-lo5-q1', competency: 'Discuss the principles of Closed-Circuit Television (CCTV) system.',
          stem: 'What does closed circuit mean in Closed-Circuit Television?',
          options: [
            'The cameras are wired in a ring',
            'The signal is carried only to its own recorder and monitors, and is not broadcast',
            'The system works without electricity',
            'The recorder is sealed and cannot be opened',
          ],
          answer: 1,
          rationale: [
            'Ring wiring is a cabling topology and has nothing to do with the name.',
            'Correct. The signal stays inside its own closed loop rather than being broadcast to anyone with a receiver.',
            'Every camera and recorder in the system needs power.',
            'Recorders are opened routinely to service or replace their disks.',
          ] },
        { kind: 'mcq', id: 'm4-lo5-q2', competency: 'Discuss the principles of Closed-Circuit Television (CCTV) system.',
          stem: 'An owner says the system is broken because last week is missing, though every camera shows a live picture. What is the most likely explanation?',
          options: [
            'Every camera has failed at once',
            'The recorder has been overwriting older footage sooner than the owner expected',
            'The monitor is on the wrong input',
            'The cable runs are too long',
          ],
          answer: 1,
          rationale: [
            'Live pictures from every camera prove the cameras are working.',
            'Correct. Retention depends on disk size, camera count and recording quality, and a system quietly overwriting after a few days looks fine until someone needs the past.',
            'A wrong input would stop the live picture too.',
            'Cable length affects picture quality, not how long recordings are kept.',
          ] },
        { kind: 'truefalse', id: 'm4-lo5-q3', competency: 'Discuss the principles of Closed-Circuit Television (CCTV) system.',
          stem: 'A camera aimed toward a bright window will still give a usable picture of anyone standing in front of it.',
          answer: false,
          rationale: 'It will not. The camera exposes for the bright background, so a person in front of it appears as a dark silhouette. Coverage means what a camera can usefully see, not merely where it points.' },
      ],
    },
  ],
}
