import type { Module } from '../lib/types'

export const m4: Module = {
  id: 'm4',
  week: 'Week 4 to 5',
  title: 'Heating Appliances and Lighting Units',
  tint: 'm4',
  teacherReviewed: false,
  competencies: [
    'Discuss the procedures in servicing appliances with heating components.',
    'Apply procedure in servicing appliances with heating components.',
    'Discuss the procedures in servicing rechargeable and electronic-controlled lighting units.',
    'Demonstrate the procedure in servicing electronic controlled lighting units.',
    'Discuss the principles of Closed-Circuit Television (CCTV) system.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Discuss the procedures in servicing appliances with heating components',
      lessons: [{
        id: 'l1',
        title: 'How a heating appliance protects itself',
        blocks: [
          { kind: 'safety', md: 'A heating appliance stays dangerously hot long after it is switched off, and a flat iron plate can burn you minutes after the power is gone. Unplug it, let it cool to the touch, and only then open it.' },
          { kind: 'text', md: 'A heating appliance turns electricity into heat on purpose, which means every one of them is built around the problem of stopping. An iron, a rice cooker, a toaster and a water heater all share the same chain: something makes the heat, something decides how much, and something cuts the power when the deciding fails.' },
          { kind: 'table',
            headers: ['Part', 'Its job', 'How it fails'],
            rows: [
              ['Heating element', 'Turns current into heat', 'Opens, usually where it enters the terminal'],
              ['Thermostat', 'Switches the element on and off to hold a setting', 'Contacts pit and stick, or stop closing at all'],
              ['Thermal fuse', 'Cuts power permanently if the appliance overheats', 'Opens once, and never closes again'],
              ['Indicator lamp', 'Shows the element is being fed', 'Fails open, which looks like a dead appliance'],
              ['Supply cord', 'Carries the current in', 'Breaks inside the sleeve near the strain relief'],
            ] },
          { kind: 'text', md: 'The thermostat and the thermal fuse are often confused, and telling them apart is most of this outcome. A thermostat is a switch that is meant to open and close thousands of times. A thermal fuse is meant to open exactly once, in an emergency, and then be replaced. If an appliance works again after cooling down, suspect the thermostat. If it never works again, suspect the fuse.' },
          { kind: 'interactive', simId: 'hotspot', config: { activity: 'flat-iron-parts' } },
          { kind: 'note', md: 'An element measured cold reads its full resistance. A 1000 watt element on 230 volts reads about 53 ohms. If you measure a few ohms, you are probably reading across the wrong pair of terminals.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm4-lo1-q1', competency: 'Discuss the procedures in servicing appliances with heating components.',
          stem: 'A rice cooker works for a while, then stops, then works again after an hour of cooling. Which part is most likely at fault?',
          options: [
            'The thermal fuse',
            'The thermostat',
            'The supply cord',
            'The heating element',
          ],
          answer: 1,
          rationale: [
            'A thermal fuse opens once and never closes again, so the appliance would not come back on its own.',
            'Correct. A thermostat that opens too early and resets on cooling produces exactly this pattern.',
            'A broken cord gives no power at all, and would not repair itself as the unit cools.',
            'An open element does not heal on cooling.',
          ] },
        { kind: 'truefalse', id: 'm4-lo1-q2', competency: 'Discuss the procedures in servicing appliances with heating components.',
          stem: 'A thermal fuse that has opened can be reset once the appliance has cooled.',
          answer: false,
          rationale: 'It cannot. A thermal fuse is a one-shot device. It opens once and must be replaced with one of the same current rating and the same temperature rating.' },
        { kind: 'mcq', id: 'm4-lo1-q3', competency: 'Discuss the procedures in servicing appliances with heating components.',
          stem: 'You measure 53 ohms across the element of a 1000 watt iron. What does that tell you?',
          options: [
            'The element is shorted',
            'The element is open',
            'The element is intact',
            'The thermostat is stuck closed',
          ],
          answer: 2,
          rationale: [
            'A shorted element would read close to zero ohms.',
            'An open element reads OL, not a sensible resistance.',
            'Correct. That is about what a 1000 watt element on 230 volts should read cold, so the element itself is fine and the fault is elsewhere.',
            'This measurement says nothing about the thermostat. Test it separately.',
          ] },
      ],
    },
    {
      id: 'lo2',
      title: 'Apply procedure in servicing appliances with heating components',
      lessons: [{
        id: 'l1',
        title: 'Finding the break in a cold iron',
        blocks: [
          { kind: 'text', md: 'The sweep for a heating appliance is the same one you learned on the fan: start at the plug and work inward, and each healthy reading rules out everything behind it. For an iron the order is cord, thermostat, thermal fuse, element.' },
          { kind: 'steps', items: [
            'Unplug the iron and let the plate cool completely.',
            'Check the cord for continuity, flexing it along its length as you measure.',
            'Check the thermostat contacts with the dial turned to maximum.',
            'Check the thermal fuse, which usually sits under the cover near the element terminals.',
            'Measure the element itself across the sole plate terminals.',
            'Replace only the part that failed, then run the iron and watch it cycle at least twice.',
          ] },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'flat-iron' } },
          { kind: 'safety', md: 'Never bridge a thermal fuse to prove a diagnosis, not even for a moment. The fuse is the only protection against a runaway element in an appliance that a user leaves face down on a board.' },
          { kind: 'note', md: 'Flexing the cord while you measure is the step most people skip. A cord that reads fine at rest can open when it is bent the way it bends in use, and that intermittent fault will come back to you a week later.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm4-lo2-q1', competency: 'Apply procedure in servicing appliances with heating components.',
          stem: 'Your continuity test on an iron reads OL across the element but the cord, thermostat and thermal fuse all pass. What do you conclude?',
          options: [
            'The thermal fuse must be retested',
            'The element is open and the sole plate assembly needs replacing',
            'The iron is safe to return',
            'The thermostat is stuck open',
          ],
          answer: 1,
          rationale: [
            'The fuse already passed. Retesting a passing part before acting on a failing one is wasted work.',
            'Correct. Everything ahead of the element passes and the element does not, so the break is in the element.',
            'An iron that will not heat is not a repaired iron.',
            'The thermostat passed its own test.',
          ] },
        { kind: 'truefalse', id: 'm4-lo2-q2', competency: 'Apply procedure in servicing appliances with heating components.',
          stem: 'A supply cord should be flexed along its length while its continuity is measured.',
          answer: true,
          rationale: 'Yes. Cords break inside the insulation from flexing, most often near the plug or the strain relief, and a break can close again at rest. Flexing while measuring is what exposes an intermittent one.' },
        { kind: 'order', id: 'm4-lo2-q3', competency: 'Apply procedure in servicing appliances with heating components.',
          stem: 'Arrange the steps for finding why a flat iron will not heat.',
          steps: [
            'Unplug the iron and let the plate cool',
            'Test the supply cord, flexing it as you measure',
            'Test the thermostat contacts at maximum',
            'Test the thermal fuse',
            'Measure the heating element',
            'Replace the failed part and watch the iron cycle twice',
          ] },
      ],
    },
  ],
}
