import type { Module } from '../lib/types'

export const m5: Module = {
  id: 'm5',
  week: 'Week 6',
  title: 'CCTV Systems',
  tint: 'm5',
  teacherReviewed: false,
  competencies: [
    'Demonstrate the procedure in CCTV system installation.',
    'Perform CCTV system servicing.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Demonstrate the procedure in CCTV system installation',
      lessons: [{
        id: 'l1',
        title: 'Planning before you drill',
        blocks: [
          { kind: 'text', md: 'An installation is decided before any hole is made. Where a camera goes fixes what it can see, and no adjustment afterwards recovers a bad position. Work out the coverage first, on paper, then mount to that plan.' },
          { kind: 'interactive', simId: 'sequence', config: { activity: 'cctv-signal' } },
          { kind: 'table',
            headers: ['Decision', 'What it settles', 'The usual mistake'],
            rows: [
              ['Camera position', 'What is in view and how large a face appears', 'Mounting high for safety, so every face is a hat'],
              ['Direction', 'Whether the sun or a window is behind the subject', 'Pointing at a doorway that is bright behind'],
              ['Cable route', 'Signal quality and how easy repair will be', 'The shortest route, through the wettest place'],
              ['Power', 'Whether every camera holds its voltage', 'One small supply feeding more cameras than it can'],
              ['Recorder position', 'Whether a thief can take the evidence with them', 'The recorder beside the front door'],
            ] },
          { kind: 'steps', items: [
            'Agree what the system must actually see, in writing, with whoever is paying for it.',
            'Walk the site and choose positions that meet that, at a height a person can be identified from.',
            'Plan cable routes that stay dry and stay reachable.',
            'Mount the cameras and run the cable without pulling it tight around corners.',
            'Terminate the connectors properly and weatherproof every outdoor joint.',
            'Power up, aim each camera against the plan, and record the final positions.',
          ] },
          { kind: 'safety', md: 'Most CCTV injuries are falls, not shocks. Use a stable platform, keep your hips inside the ladder rails, and have someone with you when you work at height. Isolate the supply before you touch any camera wiring.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm5-lo1-q1', competency: 'Demonstrate the procedure in CCTV system installation.',
          stem: 'A camera is mounted high on a wall, above head height, looking down at a doorway. What is the likely complaint?',
          options: [
            'The picture will be too bright',
            'Faces will not be identifiable, because the camera sees the tops of heads',
            'The cable run will be too long',
            'The recorder will fill too quickly',
          ],
          answer: 1,
          rationale: [
            'Height does not set exposure. What is behind the subject does.',
            'Correct. A camera mounted well above head height records hats and shoulders. Identification needs the camera near face height on the approach.',
            'Height adds very little to a cable run.',
            'Retention depends on disk size, camera count and quality, not on mounting height.',
          ] },
        { kind: 'mcq', id: 'm5-lo1-q2', competency: 'Demonstrate the procedure in CCTV system installation.',
          stem: 'Four cameras share one power supply and the picture on all four breaks up at night. What should you suspect first?',
          options: [
            'All four cameras have failed together',
            'The supply cannot hold its voltage once the night-time infrared load comes on',
            'The recorder disk is full',
            'The monitor input is faulty',
          ],
          answer: 1,
          rationale: [
            'Four simultaneous identical failures is far less likely than one shared cause.',
            'Correct. Infrared illuminators draw much more current after dark, and an undersized shared supply sags exactly then.',
            'A full disk overwrites old footage. It does not break up a live picture.',
            'A faulty monitor input would affect what is displayed, not all four pictures at a particular time of day.',
          ] },
        { kind: 'order', id: 'm5-lo1-q3', competency: 'Demonstrate the procedure in CCTV system installation.',
          stem: 'Arrange the installation steps in the correct order.',
          steps: [
            'Agree in writing what the system must see',
            'Walk the site and choose camera positions',
            'Plan cable routes that stay dry and reachable',
            'Mount the cameras and run the cable',
            'Terminate and weatherproof every joint',
            'Power up, aim against the plan, and record the positions',
          ] },
      ],
    },
    {
      id: 'lo2',
      title: 'Perform CCTV system servicing',
      lessons: [{
        id: 'l1',
        title: 'Finding which part of the chain is broken',
        blocks: [
          { kind: 'text', md: 'A CCTV fault is nearly always in one link of a chain you already know: camera, cable and connectors, recorder, monitor. The useful question is not what is broken but where the picture stops, and every test you run should move that boundary.' },
          { kind: 'text', md: 'One camera dark while the others are fine tells you the fault is in that camera path, not in the recorder or the monitor. All cameras dark tells you the opposite. Getting that distinction right before you climb a ladder saves most of the job.' },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'cctv' } },
          { kind: 'note', md: 'Outdoor connectors are where most CCTV faults live. Water gets into a joint that was never properly sealed, corrodes the centre pin, and produces a picture that works in dry weather and fails in the rain. Always open the connector and look.' },
          { kind: 'safety', md: 'Isolate the camera supply before disconnecting anything, and never work at height alone. A fall from a two metre ladder does more harm than any voltage in this system.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm5-lo2-q1', competency: 'Perform CCTV system servicing.',
          stem: 'One camera of four is black and the other three are normal. What does that rule out immediately?',
          options: [
            'The camera itself',
            'The recorder and the monitor',
            'The cable to that camera',
            'The connector at that camera',
          ],
          answer: 1,
          rationale: [
            'The camera is one of the things still in scope, not ruled out.',
            'Correct. Both are shared by all four channels, so a fault in either would affect more than one camera.',
            'That cable serves only the dark camera, so it stays in scope.',
            'That connector serves only the dark camera, so it stays in scope.',
          ] },
        { kind: 'truefalse', id: 'm5-lo2-q2', competency: 'Perform CCTV system servicing.',
          stem: 'A camera that works in dry weather and fails in the rain most likely has a water damaged connector.',
          answer: true,
          rationale: 'Yes. A fault that tracks the weather is a fault that water reaches. The usual place is an outdoor joint that was never properly sealed, where corrosion on the centre pin makes contact that comes and goes.' },
        { kind: 'order', id: 'm5-lo2-q3', competency: 'Perform CCTV system servicing.',
          stem: 'Arrange the steps for finding why one camera shows no picture.',
          steps: [
            'Confirm the other cameras are normal',
            'Isolate the camera supply',
            'Check the voltage at the camera end',
            'Open and inspect the connector at the camera',
            'Test the cable run',
            'Substitute a camera known to be working',
          ] },
      ],
    },
  ],
}
