import type { Module } from '../lib/types'

export const m6: Module = {
  id: 'm6',
  week: 'Week 7',
  title: 'Fire Alarm Principles and Installation',
  tint: 'm6',
  teacherReviewed: false,
  competencies: [
    'Discuss the principles of fire alarm systems.',
    'Perform the procedure in fire alarm system installation.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Discuss the principles of fire alarm systems',
      lessons: [{
        id: 'l1',
        title: 'How a fire alarm knows and how it tells',
        blocks: [
          { kind: 'text', md: 'A fire alarm system does two things. It notices, through detectors and manual call points, and it warns, through sounders and strobes. A control panel sits between them, watching every zone and deciding what happens when one of them activates.' },
          { kind: 'interactive', simId: 'sequence', config: { activity: 'fas-signal' } },
          { kind: 'table',
            headers: ['Device', 'What it responds to', 'Where it belongs'],
            rows: [
              ['Smoke detector', 'Smoke particles in the chamber', 'Escape routes, corridors, sleeping areas'],
              ['Heat detector', 'Temperature, or a fast rise in it', 'Kitchens and garages, where smoke is normal'],
              ['Manual call point', 'A person deciding to raise the alarm', 'On every exit route, at a height anyone can reach'],
              ['Sounder', 'The panel telling it to sound', 'Everywhere the alarm must be heard, including bathrooms'],
              ['Control panel', 'Every zone, all the time', 'Near the main entrance, where the fire service will look'],
            ] },
          { kind: 'text', md: 'The panel does not only watch for fire. It watches the wiring itself. A conventional zone carries an end of line resistor at the last device, and the panel reads that standing resistance continuously. Break the wire and the resistance goes open, so the panel reports a fault. Short the wire and the resistance goes to zero, so the panel reports an alarm. That is why a fire alarm can tell the difference between a fire and a broken cable, and why the end of line resistor is not optional.' },
          { kind: 'note', md: 'A heat detector in a kitchen is not a downgrade. A smoke detector there would go off every time someone fries fish, and a system people disable is worse than no system.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm6-lo1-q1', competency: 'Discuss the principles of fire alarm systems.',
          stem: 'Why does a conventional zone need an end of line resistor?',
          options: [
            'It limits the current through the detectors',
            'It gives the panel a standing resistance to monitor, so a break reads as a fault',
            'It powers the last detector on the zone',
            'It makes the sounders louder',
          ],
          answer: 1,
          rationale: [
            'Detector current is set by the panel and the devices, not by the end of line resistor.',
            'Correct. The panel watches that resistance continuously, so an open wire reads as a fault and a short reads as an alarm.',
            'Detectors are powered from the zone pair, not by the resistor.',
            'Sounders are on their own circuit and the resistor has no effect on them.',
          ] },
        { kind: 'mcq', id: 'm6-lo1-q2', competency: 'Discuss the principles of fire alarm systems.',
          stem: 'Which detector belongs in a kitchen?',
          options: [
            'A smoke detector, because kitchens are high risk',
            'A heat detector, because normal cooking would set off a smoke detector',
            'No detector, because kitchens are always occupied',
            'A manual call point only',
          ],
          answer: 1,
          rationale: [
            'The risk is real, but a detector that cries wolf gets disabled, and a disabled detector protects nobody.',
            'Correct. A heat detector ignores cooking smoke and still responds to an actual fire.',
            'A kitchen is one of the likeliest places for a fire to start and must be covered.',
            'A call point needs a person present and deciding. It is not detection.',
          ] },
        { kind: 'truefalse', id: 'm6-lo1-q3', competency: 'Discuss the principles of fire alarm systems.',
          stem: 'A short circuit across a conventional zone makes the panel report a fault.',
          answer: false,
          rationale: 'It reports an alarm, not a fault. A detector in alarm puts a low resistance across the zone, which is why a low reading means alarm and an open reading means fault. That is also why many panels can tell a dead short from a genuine activation, because a detector in alarm presents a defined resistance rather than zero ohms.' },
      ],
    },
    {
      id: 'lo2',
      title: 'Perform the procedure in fire alarm system installation',
      lessons: [{
        id: 'l1',
        title: 'Installing a zone that the panel will trust',
        blocks: [
          { kind: 'safety', md: 'Tell the responsible person before you put any part of a fire alarm out of service, isolate the sounders so testing does not evacuate the building, and never leave a system disabled at the end of a day without telling someone in writing. The panel enclosure carries mains voltage and a standby battery that can push a very high current into a short circuit. Do not open it or work at its terminals without your teacher present.' },
          { kind: 'text', md: 'Installation is mostly about making a circuit the panel can monitor honestly. Devices go in order along the zone, the end of line resistor goes at the last one and nowhere else, and every joint is made in an enclosure that can be found again.' },
          { kind: 'steps', items: [
            'Plan the zone so every device on it is in one identifiable area of the building.',
            'Run the cable in order, device to device, without spurs.',
            'Fit each base, keeping the wiring polarity consistent all the way along.',
            'Fit the end of line resistor at the last device on the zone.',
            'Fit the heads, check each one latches, and label every device with its position.',
            'Test each device in turn from the panel and record the result against the device list.',
          ] },
          { kind: 'note', md: 'Fitting the end of line resistor at the panel instead of the last device makes the panel read a healthy zone that it is not actually monitoring. Everything downstream could be cut and the panel would never know.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm6-lo2-q1', competency: 'Perform the procedure in fire alarm system installation.',
          stem: 'What is wrong with fitting the end of line resistor inside the panel?',
          options: [
            'It is harder to reach later',
            'The panel then reads a healthy zone whether or not the wiring beyond it is intact',
            'It draws too much current',
            'It makes the zone respond too slowly',
          ],
          answer: 1,
          rationale: [
            'Access is a nuisance, not the reason it is dangerous.',
            'Correct. The resistor is what the panel monitors, so putting it at the panel means the entire zone could be cut with no fault shown.',
            'The current through an end of line resistor is tiny wherever it sits.',
            'Position does not affect response time.',
          ] },
        { kind: 'truefalse', id: 'm6-lo2-q2', competency: 'Perform the procedure in fire alarm system installation.',
          stem: 'You may leave a fire alarm zone isolated overnight if you plan to finish the work tomorrow.',
          answer: false,
          rationale: 'Not without telling the responsible person in writing and agreeing what protects that area meanwhile. An isolated zone is an unprotected area, and the people sleeping in it do not know.' },
        { kind: 'order', id: 'm6-lo2-q3', competency: 'Perform the procedure in fire alarm system installation.',
          stem: 'Arrange the steps for installing a conventional zone.',
          steps: [
            'Plan the zone to cover one identifiable area',
            'Run the cable device to device, without spurs',
            'Fit each base with consistent polarity',
            'Fit the end of line resistor at the last device',
            'Fit and latch the heads, and label each position',
            'Test each device from the panel and record the result',
          ] },
      ],
    },
  ],
}
