import type { Module } from '../lib/types'

export const m7: Module = {
  id: 'm7',
  week: 'Week 8',
  title: 'Fire Alarm Servicing and Audio Introduction',
  tint: 'm7',
  teacherReviewed: false,
  competencies: [
    'Perform the procedure in fire alarm system servicing.',
    'Discuss audio products and systems.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Perform the procedure in fire alarm system servicing',
      lessons: [{
        id: 'l1',
        title: 'Reading what the panel is telling you',
        blocks: [
          { kind: 'safety', md: 'Before any servicing, tell the responsible person, isolate the sounders so a test does not evacuate the building, and write down the time each zone goes out of service. Stay with the system until every zone is back in service, and never go home leaving one disabled without a signed handover.' },
          { kind: 'text', md: 'The panel has already done most of the diagnosis for you. A fault on one zone means the resistance it monitors has gone open, so the break is in that zone, between the panel and the end of line resistor. Your job is to find where along that path it stopped.' },
          { kind: 'text', md: 'Work outward from the panel, halving the zone as you go. Measure at the panel, then at the first junction, then further along, and each measurement tells you which side of that point the break is on. That is far quicker than opening every device in order.' },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'fas-zone' } },
          { kind: 'table',
            headers: ['What the panel shows', 'What it means', 'Where to look'],
            rows: [
              ['Fault on one zone', 'That zone reads open', 'A break, a loose terminal, or a missing end of line resistor'],
              ['Fault on every zone', 'Something common has failed', 'Panel supply, standby battery, or the panel itself'],
              ['Alarm with no fire', 'That zone reads shorted', 'A wet or damaged device, or a pinched cable'],
              ['One device not responding', 'That device alone is not making the circuit', 'A head not latched, or a failed head'],
            ] },
          { kind: 'note', md: 'A missing end of line resistor and a broken wire look identical at the panel. Both read open. The difference shows up when you measure at the last device: the resistor is either there or it is not.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm7-lo1-q1', competency: 'Perform the procedure in fire alarm system servicing.',
          stem: 'The panel reports a fault on zone 2 only. What does that tell you?',
          options: [
            'The panel itself has failed',
            'The circuit zone 2 monitors has gone open somewhere between the panel and the end of line resistor',
            'A detector on zone 2 has activated',
            'The standby battery is flat',
          ],
          answer: 1,
          rationale: [
            'A panel fault would show on every zone, not one.',
            'Correct. A fault on a single zone is that zone reading open, and the break is somewhere along its path.',
            'An activation reads as a short, which the panel reports as an alarm, not a fault.',
            'A flat battery is a common fault affecting the whole panel, not one zone.',
          ] },
        { kind: 'mcq', id: 'm7-lo1-q2', competency: 'Perform the procedure in fire alarm system servicing.',
          stem: 'You find the zone reads open at the panel and open at the first junction, but correct at the last device. Where is the break?',
          options: [
            'Between the last device and the end of line resistor',
            'Between the panel and the first junction',
            'Inside the panel',
            'There is no break',
          ],
          answer: 1,
          rationale: [
            'The last device reads correctly, so everything from there back through the resistor is intact.',
            'Correct. The reading is bad at the panel and at the first junction but good further along, so the break is in the section you have not yet proved, between the panel and that junction.',
            'A panel fault would not clear when you measure further along the zone.',
            'A zone reading open at two points is a break.',
          ] },
        { kind: 'truefalse', id: 'm7-lo1-q3', competency: 'Perform the procedure in fire alarm system servicing.',
          stem: 'A missing end of line resistor and a broken zone wire look the same at the panel.',
          answer: true,
          rationale: 'They do. Both make the zone read open, so the panel reports the same fault for either. Only a measurement at the last device separates them.' },
      ],
    },
    {
      id: 'lo2',
      title: 'Discuss audio products and systems',
      lessons: [{
        id: 'l1',
        title: 'What a sound system is made of',
        blocks: [
          { kind: 'text', md: 'A sound system moves one thing along a chain, and every part of that chain either changes the signal on purpose or leaves it alone. Sound goes into a microphone and becomes a small electrical signal. A mixer combines and shapes it. An amplifier makes it powerful enough to move a cone. A speaker turns it back into sound.' },
          { kind: 'table',
            headers: ['Stage', 'What it does', 'Its usual fault'],
            rows: [
              ['Microphone', 'Turns sound into a very small signal', 'Damaged cable at the connector, from being pulled'],
              ['Mixer', 'Combines sources and sets levels', 'A channel left muted, or gain set far too high'],
              ['Amplifier', 'Raises the signal enough to drive a speaker', 'Protection cuts in from a shorted speaker line'],
              ['Speaker', 'Turns the signal back into sound', 'A blown driver from long term overdriving'],
              ['Cabling', 'Carries the signal between stages', 'Intermittent joints, especially at plugs'],
            ] },
          { kind: 'text', md: 'Two ideas explain most of what goes wrong. Gain structure means setting each stage so it passes a healthy signal without pushing the next one into distortion, and most bad sound is a gain set wrong somewhere earlier in the chain. Feedback is the howl you get when a microphone hears its own speaker, and it is fixed by moving or aiming, not by turning things down.' },
          { kind: 'note', md: 'Before diagnosing a fault, check what is muted. A muted channel, a wrong input selected, and a speaker unplugged account for more silent systems than every genuine electronic failure put together.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm7-lo2-q1', competency: 'Discuss audio products and systems.',
          stem: 'A public address system howls whenever the speaker is turned up. What is the cause?',
          options: [
            'The amplifier is faulty',
            'The microphone is hearing the speaker, so the signal goes round the loop',
            'The speaker cable is too long',
            'The mixer channel is muted',
          ],
          answer: 1,
          rationale: [
            'The amplifier is doing exactly what it is asked to do.',
            'Correct. That is feedback. The cure is to move or aim the microphone and the speaker so one does not hear the other.',
            'Cable length affects losses, not feedback.',
            'A muted channel produces silence, not a howl.',
          ] },
        { kind: 'mcq', id: 'm7-lo2-q2', competency: 'Discuss audio products and systems.',
          stem: 'A system sounds distorted at every volume setting. Where should you look first?',
          options: [
            'The speaker',
            'The gain structure, starting at the first stage the signal enters',
            'The mains supply',
            'The room acoustics',
          ],
          answer: 1,
          rationale: [
            'A blown driver distorts, but distortion at every level usually arrives already in the signal.',
            'Correct. If a stage early in the chain is overdriven, everything after it faithfully reproduces that distortion, so turning down later changes nothing.',
            'A supply problem usually shows as hum or as the unit shutting down.',
            'Room acoustics change tone and clarity, not distortion at every level.',
          ] },
        { kind: 'truefalse', id: 'm7-lo2-q3', competency: 'Discuss audio products and systems.',
          stem: 'Before diagnosing a silent audio system, it is worth checking for a muted channel or a wrong input.',
          answer: true,
          rationale: 'Always. A muted channel, a wrong input selected and an unplugged speaker account for more silent systems than genuine electronic faults do, and all three take seconds to rule out.' },
      ],
    },
  ],
}
