import type { Module } from '../lib/types'

export const m8: Module = {
  id: 'm8',
  week: 'Week 9',
  title: 'Audio Products and Systems',
  tint: 'm8',
  teacherReviewed: false,
  competencies: [
    'Perform the installation and operation of audio products and systems.',
    'Perform procedure in servicing audio products and systems.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Perform the installation and operation of audio products and systems',
      lessons: [{
        id: 'l1',
        title: 'Setting up a system that stays clean',
        blocks: [
          { kind: 'text', md: 'Setting up a sound system is mostly about two decisions made before anything is switched on: where the speakers go relative to the microphones, and how much gain each stage is given. Get those right and the system behaves. Get them wrong and no amount of adjustment later will rescue it.' },
          { kind: 'interactive', simId: 'sequence', config: { activity: 'audio-signal' } },
          { kind: 'text', md: 'Speakers must end up in front of the microphones, meaning closer to the audience than the microphone is, so the microphone sits behind the sound it would otherwise pick up. A speaker placed behind a presenter is the single most common cause of feedback at a school event.' },
          { kind: 'steps', items: [
            'Place the speakers so they face the audience and sit ahead of every microphone position.',
            'Connect the system from the microphone forward, leaving the amplifier switched off.',
            'Switch on in order, sources first and the power amplifier last.',
            'Set each channel gain so a normal speaking voice reaches most of the meter without lighting the peak indicator.',
            'Raise the master until the room is covered, then stop.',
            'Walk the room while someone speaks, listening for dead spots and for the onset of feedback.',
          ] },
          { kind: 'note', md: 'Switch the power amplifier on last and off first. Every other unit produces a thump on its output as it powers up, and the amplifier will faithfully deliver that thump to the speakers.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm8-lo1-q1', competency: 'Perform the installation and operation of audio products and systems.',
          stem: 'Why is the power amplifier switched on last and switched off first?',
          options: [
            'It takes longest to warm up',
            'Other units thump as they power up, and the amplifier would deliver that thump to the speakers',
            'It draws the most current',
            'It must charge its capacitors before the mixer starts',
          ],
          answer: 1,
          rationale: [
            'Warm up time is not the reason, and modern amplifiers need none.',
            'Correct. A switch-on transient from a source or mixer becomes a damaging thump once an amplifier is already live.',
            'Current draw does not set the switching order.',
            'The amplifier charges its own supply in either order.',
          ] },
        { kind: 'mcq', id: 'm8-lo1-q2', competency: 'Perform the installation and operation of audio products and systems.',
          stem: 'A speaker is placed behind the presenter so the audience can hear better. What will happen?',
          options: [
            'The sound will be clearer for the audience',
            'The microphone will hear the speaker and the system will feed back',
            'The amplifier will overheat',
            'The presenter will hear themselves too quietly',
          ],
          answer: 1,
          rationale: [
            'Sound behind the presenter reaches the audience later and weaker, not clearer.',
            'Correct. The microphone is now in front of the speaker, which is the condition for feedback.',
            'Placement does not change amplifier temperature.',
            'They will hear themselves louder, which is part of the problem.',
          ] },
        { kind: 'order', id: 'm8-lo1-q3', competency: 'Perform the installation and operation of audio products and systems.',
          stem: 'Arrange the steps for setting up a small sound system.',
          steps: [
            'Place the speakers ahead of every microphone position',
            'Connect from the microphone forward with the amplifier off',
            'Switch on sources first and the power amplifier last',
            'Set each channel gain against a normal speaking voice',
            'Raise the master until the room is covered',
            'Walk the room listening for dead spots and feedback',
          ] },
      ],
    },
    {
      id: 'lo2',
      title: 'Perform procedure in servicing audio products and systems',
      lessons: [{
        id: 'l1',
        title: 'Finding where the sound stops',
        blocks: [
          { kind: 'safety', md: 'The filter capacitors in an amplifier supply hold their charge long after the mains is removed, and a large amplifier stores enough to injure you. Unplug it, discharge them through a bleeder resistor, and confirm with a meter before you touch the board.' },
          { kind: 'text', md: 'One channel silent while the other plays is the most useful symptom in audio servicing, because the working channel is a reference. Anything shared by both channels is ruled out immediately, and every test becomes a comparison rather than a judgement.' },
          { kind: 'text', md: 'Swapping is the technique that does most of the work. Swap the input leads and see whether the silence follows. Swap the speaker leads and see whether it follows. Each swap moves the boundary of the fault without any measurement at all.' },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'amp' } },
          { kind: 'note', md: 'Set the volume low before every test. A fault that is intermittent can restore full output without warning, and a speaker at full output beside your head is a hearing injury.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm8-lo2-q1', competency: 'Perform procedure in servicing audio products and systems.',
          stem: 'You swap the left and right input leads and the silence stays on the right channel. What does that tell you?',
          options: [
            'The right input lead is faulty',
            'The fault is inside the amplifier or after it, not in the input lead',
            'The mixer is faulty',
            'Both channels are faulty',
          ],
          answer: 1,
          rationale: [
            'If the lead were faulty the silence would have followed it to the left channel.',
            'Correct. The silence stayed with the channel rather than the lead, so the fault is downstream of the input.',
            'A mixer fault upstream would have moved with the lead.',
            'The left channel is playing normally.',
          ] },
        { kind: 'truefalse', id: 'm8-lo2-q2', competency: 'Perform procedure in servicing audio products and systems.',
          stem: 'With one channel working, that channel can be used as a reference for every measurement on the faulty one.',
          answer: true,
          rationale: 'Yes, and that is what makes this symptom so useful. Every reading on the dead channel can be compared with the same point on the working one, so you are looking for a difference rather than judging an absolute value.' },
        { kind: 'order', id: 'm8-lo2-q3', competency: 'Perform procedure in servicing audio products and systems.',
          stem: 'Arrange the steps for finding why one channel is silent.',
          steps: [
            'Swap the input leads and see whether the silence follows',
            'Compare the supply rails feeding each output stage',
            'Compare the output at each pair of speaker terminals',
            'Unplug the amplifier and discharge the supply capacitors',
            'Test the speaker lead and the driver on the silent side',
            'Repair, then run both channels and compare them by ear',
          ] },
      ],
    },
  ],
}
