import type { Module } from '../lib/types'

export const m9: Module = {
  id: 'm9',
  week: 'Week 10 to 11',
  title: 'Television, Control Boards, Sensors and Actuators',
  tint: 'm9',
  teacherReviewed: false,
  competencies: [
    'Discuss television.',
    'Perform the procedure in servicing television.',
    'Discuss control boards and motor controllers.',
    'Perform the procedure in servicing control boards and motor controllers.',
    'Discuss sensors and actuators.',
    'Perform the procedure in servicing sensors and actuators.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Discuss television',
      lessons: [{
        id: 'l1',
        title: 'What is behind the screen',
        blocks: [
          { kind: 'safety', md: 'A television panel is a large sheet of glass held in a thin frame. Never lever it, twist the set, or lay it on an uneven surface. A cracked panel cannot be repaired and ends the job, and the broken edge is sharp enough to cut through a glove.' },
          { kind: 'text', md: 'A flat screen television is four blocks behind one sheet of glass. A power supply board turns the mains into the rails everything else needs. A main board takes the incoming signal and turns it into video. A timing board takes that video and drives the panel row by row. The backlight lights the panel from behind so you can see the result.' },
          { kind: 'interactive', simId: 'hotspot', config: { activity: 'tv-boards' } },
          { kind: 'text', md: 'Knowing those four blocks tells you what a symptom means before you open anything. Sound but no picture usually means the signal path is working and the light is not. No sound and no picture with a dead standby light means the supply. A picture with no sound means the audio output, not the panel.' },
          { kind: 'note', md: 'Televisions have changed a great deal, and the old high voltage danger of a cathode ray tube is gone. What replaced it is a large filter capacitor bank in the supply, which still holds a charge that will hurt you, and a fragile panel that is expensive to break.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo1-q1', competency: 'Discuss television.',
          stem: 'A set has normal sound and responds to the remote, but the screen is black. Which block is working?',
          options: [
            'Only the power supply',
            'The power supply and the signal path, since sound is being produced',
            'The backlight',
            'None of them',
          ],
          answer: 1,
          rationale: [
            'Sound requires more than the supply alone.',
            'Correct. Sound and remote response prove the supply and the signal path are alive, which points at the light rather than the picture.',
            'A working backlight would give a visible screen.',
            'Sound proves several blocks are working.',
          ] },
        { kind: 'mcq', id: 'm9-lo1-q2', competency: 'Discuss television.',
          stem: 'Which board has the aerial socket on it?',
          options: [
            'The power supply board',
            'The main board',
            'The timing board',
            'The backlight driver',
          ],
          answer: 1,
          rationale: [
            'The power supply board carries the mains inlet, not the aerial.',
            'Correct. The main board receives and decodes the incoming signal, so the aerial and the other inputs land there.',
            'The timing board sits between the main board and the panel and has no external connectors.',
            'The backlight driver only powers the lighting.',
          ] },
        { kind: 'truefalse', id: 'm9-lo1-q3', competency: 'Discuss television.',
          stem: 'A cracked panel can usually be repaired if the crack is small.',
          answer: false,
          rationale: 'It cannot. The panel is a sealed assembly and a crack anywhere in it ends the repair. Tell the owner before doing anything else, because the set is normally not economic to fix.' },
      ],
    },
    {
      id: 'lo2',
      title: 'Perform the procedure in servicing television',
      lessons: [{
        id: 'l1',
        title: 'The torch test and what follows it',
        blocks: [
          { kind: 'safety', md: 'Unplug the set, discharge the large filter capacitors on the power supply board through a bleeder resistor, and then confirm with the meter that they read close to zero volts before touching the board. Lay the set face down on a clean flat surface with the stand removed, and get help to turn it.' },
          { kind: 'text', md: 'Sound with a black screen has one quick test that decides the whole job. Shine a torch at the screen at a shallow angle in a dark room and look closely. If you can see a faint but complete picture, the panel is being driven correctly and only the light is missing, so the fault is the backlight. If you see nothing, the picture is not being produced at all and the fault is further back.' },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'tv' } },
          { kind: 'table',
            headers: ['What you see', 'What is proven', 'Where to look next'],
            rows: [
              ['Faint picture under a torch', 'The panel and the signal path are working', 'The backlight and its driver'],
              ['Nothing under a torch, sound normal', 'The supply and the audio path are working', 'The main board and the timing board'],
              ['No sound, no picture, no standby light', 'Very little', 'The power supply board'],
              ['A crack visible under the torch', 'The panel is broken', 'Stop, and tell the owner'],
            ] },
          { kind: 'note', md: 'Do the torch test before opening the set. It costs nothing, takes ten seconds, and it decides whether the job is a backlight strip or a board.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo2-q1', competency: 'Perform the procedure in servicing television.',
          stem: 'Under a torch you can see a faint but complete picture on a black screen. What does that prove?',
          options: [
            'The panel is cracked',
            'The panel is being driven correctly and only the lighting is missing',
            'The power supply has failed',
            'The main board has failed',
          ],
          answer: 1,
          rationale: [
            'A crack would be visible as a line, not as a complete faint picture.',
            'Correct. A complete image means the signal path and the panel are both working, so what is missing is light.',
            'A failed supply would give no sound and no standby light.',
            'A failed main board would give no picture to see, even under a torch.',
          ] },
        { kind: 'truefalse', id: 'm9-lo2-q2', competency: 'Perform the procedure in servicing television.',
          stem: 'The torch test should be done before opening the set.',
          answer: true,
          rationale: 'Yes. It takes ten seconds, needs no tools, and decides whether the fault is the backlight or something further back. Opening the set first risks damage for no information.' },
        { kind: 'order', id: 'm9-lo2-q3', competency: 'Perform the procedure in servicing television.',
          stem: 'Arrange the steps for a set with sound but no picture.',
          steps: [
            'Confirm the sound and the remote response',
            'Do the torch test with the set switched on',
            'Unplug the set and discharge the supply capacitors',
            'Lay the set face down with the stand removed',
            'Measure the backlight driver output',
            'Replace the failed part and confirm an even picture',
          ] },
      ],
    },
  ],
}
