import type { Module } from '../lib/types'

export const m9: Module = {
  id: 'm9',
  week: 'Week 10 to 11',
  title: 'Television, Control Boards, Sensors and Actuators',
  tint: 'm9',
  teacherReviewed: false,
  competencies: [
    'Discuss television.',
    'Perform the procedure in servicing television.',
    'Discuss control boards and motor controllers.',
    'Perform the procedure in servicing control boards and motor controllers.',
    'Discuss sensors and actuators.',
    'Perform the procedure in servicing sensors and actuators.',
  ],
  outcomes: [
    {
      id: 'lo1',
      title: 'Discuss television',
      lessons: [{
        id: 'l1',
        title: 'What is behind the screen',
        blocks: [
          { kind: 'safety', md: 'A television panel is a large sheet of glass held in a thin frame. Never lever it, twist the set, or lay it on an uneven surface. A cracked panel cannot be repaired and ends the job, and the broken edge is sharp enough to cut through a glove.' },
          { kind: 'text', md: 'A flat screen television is four blocks behind one sheet of glass. A power supply board turns the mains into the rails everything else needs. A main board takes the incoming signal and turns it into video. A timing board takes that video and drives the panel row by row. The backlight lights the panel from behind so you can see the result.' },
          { kind: 'interactive', simId: 'hotspot', config: { activity: 'tv-boards' } },
          { kind: 'text', md: 'Knowing those four blocks tells you what a symptom means before you open anything. Sound but no picture usually means the signal path is working and the light is not. No sound and no picture with a dead standby light means the supply. A picture with no sound means the audio output, not the panel.' },
          { kind: 'note', md: 'Televisions have changed a great deal, and the old high voltage danger of a cathode ray tube is gone. What replaced it is a large filter capacitor bank in the supply, which still holds a charge that will hurt you, and a fragile panel that is expensive to break.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo1-q1', competency: 'Discuss television.',
          stem: 'A set has normal sound and responds to the remote, but the screen is black. Which block is working?',
          options: [
            'Only the power supply',
            'The backlight',
            'The power supply and the signal path, since sound is being produced',
            'None of them',
          ],
          answer: 2,
          rationale: [
            'Sound requires more than the supply alone.',
            'A working backlight would give a visible screen.',
            'Correct. Sound and remote response prove the supply and the signal path are alive, which points at the light rather than the picture.',
            'Sound proves several blocks are working.',
          ] },
        { kind: 'mcq', id: 'm9-lo1-q2', competency: 'Discuss television.',
          stem: 'Which board has the aerial socket on it?',
          options: [
            'The power supply board',
            'The main board',
            'The timing board',
            'The backlight driver',
          ],
          answer: 1,
          rationale: [
            'The power supply board carries the mains inlet, not the aerial.',
            'Correct. The main board receives and decodes the incoming signal, so the aerial and the other inputs land there.',
            'The timing board sits between the main board and the panel and has no external connectors.',
            'The backlight driver only powers the lighting.',
          ] },
        { kind: 'truefalse', id: 'm9-lo1-q3', competency: 'Discuss television.',
          stem: 'A cracked panel can usually be repaired if the crack is small.',
          answer: false,
          rationale: 'It cannot. The panel is a sealed assembly and a crack anywhere in it ends the repair. Tell the owner before doing anything else, because the set is normally not economic to fix.' },
      ],
    },
    {
      id: 'lo2',
      title: 'Perform the procedure in servicing television',
      lessons: [{
        id: 'l1',
        title: 'The torch test and what follows it',
        blocks: [
          { kind: 'safety', md: 'Unplug the set, discharge the large filter capacitors on the power supply board through a bleeder resistor, and then confirm with the meter that they read close to zero volts before touching the board. Lay the set face down on a clean flat surface with the stand removed, and get help to turn it.' },
          { kind: 'text', md: 'Sound with a black screen has one quick test that decides the whole job. Shine a torch at the screen at a shallow angle in a dark room and look closely. If you can see a faint but complete picture, the panel is being driven correctly and only the light is missing, so the fault is the backlight. If you see nothing, the picture is not being produced at all and the fault is further back.' },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'tv' } },
          { kind: 'table',
            headers: ['What you see', 'What is proven', 'Where to look next'],
            rows: [
              ['Faint picture under a torch', 'The panel and the signal path are working', 'The backlight and its driver'],
              ['Nothing under a torch, sound normal', 'The supply and the audio path are working', 'The main board and the timing board'],
              ['No sound, no picture, no standby light', 'Very little', 'The power supply board'],
              ['A crack visible under the torch', 'The panel is broken', 'Stop, and tell the owner'],
            ] },
          { kind: 'note', md: 'Do the torch test before opening the set. It costs nothing, takes ten seconds, and it decides whether the job is a backlight strip or a board.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo2-q1', competency: 'Perform the procedure in servicing television.',
          stem: 'Under a torch you can see a faint but complete picture on a black screen. What does that prove?',
          options: [
            'The panel is cracked',
            'The power supply has failed',
            'The panel is being driven correctly and only the lighting is missing',
            'The main board has failed',
          ],
          answer: 2,
          rationale: [
            'A crack would be visible as a line, not as a complete faint picture.',
            'A failed supply would give no sound and no standby light.',
            'Correct. A complete image means the signal path and the panel are both working, so what is missing is light.',
            'A failed main board would give no picture to see, even under a torch.',
          ] },
        { kind: 'truefalse', id: 'm9-lo2-q2', competency: 'Perform the procedure in servicing television.',
          stem: 'The torch test should be done before opening the set.',
          answer: true,
          rationale: 'Yes. It takes ten seconds, needs no tools, and decides whether the fault is the backlight or something further back. Opening the set first risks damage for no information.' },
        { kind: 'order', id: 'm9-lo2-q3', competency: 'Perform the procedure in servicing television.',
          stem: 'Arrange the steps for a set with sound but no picture.',
          steps: [
            'Confirm the sound and the remote response',
            'Do the torch test with the set switched on',
            'Unplug the set, lay it face down and remove the back',
            'Restore the supply and measure the backlight driver output',
            'Unplug the set again and discharge the supply capacitors',
            'Replace the failed part, restore the supply and confirm an even picture',
          ] },
      ],
    },
    {
      id: 'lo3',
      title: 'Discuss control boards and motor controllers',
      lessons: [{
        id: 'l1',
        title: 'How a board keeps the mains away from the logic',
        blocks: [
          { kind: 'text', md: 'A control board has two halves that must never meet. One half runs at mains voltage and switches the load. The other runs at a few volts and makes the decisions. Almost everything else on the board exists to let those two halves talk to each other without touching.' },
          { kind: 'interactive', simId: 'match', config: { activity: 'control-board' } },
          { kind: 'table',
            headers: ['Part', 'Which side', 'What it does'],
            rows: [
              ['Microcontroller', 'Logic', 'Reads inputs, decides, drives outputs'],
              ['Voltage regulator', 'Logic', 'Holds a steady rail, and runs warm doing it'],
              ['Opto isolator', 'Between', 'Passes a signal as light, with no electrical path'],
              ['Relay', 'Between', 'Switches the load, with a coil the logic drives through a transistor'],
              ['Electrolytic capacitor', 'Either', 'Smooths the supply, and bulges on top when it fails'],
            ] },
          { kind: 'text', md: 'A motor controller adds one more idea: it decides not just whether the motor runs but how. Direction comes from which way current is sent through a DC motor, and speed comes from switching the supply on and off quickly enough that the motor averages it out rather than stuttering.' },
          { kind: 'safety', md: 'The mains half of a control board is live whenever the appliance is plugged in, including parts that look like ordinary low voltage components. Isolate before touching anything on the board, and never assume the logic half is safe because it is only a few volts.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo3-q1', competency: 'Discuss control boards and motor controllers.',
          stem: 'What does an opto isolator do on a control board?',
          options: [
            'It smooths the supply to the logic',
            'It passes a signal across a gap using light, so the two sides never touch electrically',
            'It switches the motor directly',
            'It holds the logic supply steady',
          ],
          answer: 1,
          rationale: [
            'That is the electrolytic capacitor.',
            'Correct. Light crosses the gap and current does not, which is what keeps a mains fault out of the logic and out of anything connected to it.',
            'The relay or a semiconductor switch does that. An opto isolator carries a signal, not a load.',
            'That is the voltage regulator.',
          ] },
        { kind: 'mcq', id: 'm9-lo3-q2', competency: 'Discuss control boards and motor controllers.',
          stem: 'You see an electrolytic capacitor with a domed top on a board that behaves erratically. What is the likely significance?',
          options: [
            'It is normal and can be ignored',
            'It affects the relay contacts',
            'It means the board has been overvoltaged only',
            'The capacitor has failed, and the supply it smooths is probably no longer steady',
          ],
          answer: 3,
          rationale: [
            'A flat top is normal. A domed or split top is a failed capacitor.',
            'The contacts are a separate part and a separate failure.',
            'Overvoltage is one cause, but heat and age are more common, and the conclusion is the same.',
            'Correct. A bulged capacitor has vented, its capacitance has collapsed, and whatever it was smoothing now carries ripple that makes logic behave unpredictably.',
          ] },
        { kind: 'truefalse', id: 'm9-lo3-q3', competency: 'Discuss control boards and motor controllers.',
          stem: 'The low voltage half of a control board is safe to touch while the appliance is plugged in.',
          answer: false,
          rationale: 'It is not. The two halves share a board, a fault can bridge them, and some boards have no isolation at all and sit at mains potential throughout. Isolate before touching any part of it.' },
      ],
    },
    {
      id: 'lo4',
      title: 'Perform the procedure in servicing control boards and motor controllers',
      lessons: [{
        id: 'l1',
        title: 'Following the decision, not the wire',
        blocks: [
          { kind: 'safety', md: 'Isolate the supply and lock it off before opening the enclosure, because a motor can start on its own when a control signal changes. Prove the load side is dead with the meter before you touch it. Keep hands, sleeves and tools clear of the driven mechanism even with the supply removed, and tell whoever operates the machine that it is out of service rather than leaving a note.' },
          { kind: 'text', md: 'On a control board the useful question is not where the current stops but where the decision stops being obeyed. Follow it in order: the sensor or switch that provides the information, the wiring that carries it, the controller input that receives it, the output that acts on it, and finally the device that output drives.' },
          { kind: 'interactive', simId: 'troubleshoot', config: { scenario: 'motor-control' } },
          { kind: 'text', md: 'A relay is where that chain most often fails, and it fails in two opposite ways. An open coil means the relay never operates, so the load never runs. Welded contacts mean the relay never releases, so the load never stops. The second is the more dangerous, because the machine keeps moving when it has been told to halt.' },
          { kind: 'note', md: 'Welded contacts are a symptom, not the disease. They weld because the relay has been switching more current than it is rated for, usually a motor whose starting surge exceeds the contact rating. Fit a new relay without finding that out and it will weld too.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo4-q1', competency: 'Perform the procedure in servicing control boards and motor controllers.',
          stem: 'A motor runs but will not stop when the limit switch operates. The switch tests good and the controller input changes state correctly. What should you suspect?',
          options: [
            'The limit switch after all',
            'The relay contacts have welded closed',
            'The relay coil is open',
            'The motor is faulty',
          ],
          answer: 1,
          rationale: [
            'The switch has already been tested and it operates correctly.',
            'Correct. The controller is deciding to stop and the relay is not obeying, which means the contacts are still passing current with no coil voltage.',
            'An open coil would stop the relay ever pulling in, so the motor would never run.',
            'The motor is doing exactly what the current reaching it tells it to do.',
          ] },
        { kind: 'truefalse', id: 'm9-lo4-q2', competency: 'Perform the procedure in servicing control boards and motor controllers.',
          stem: 'Fitting a new relay is a complete repair for welded contacts.',
          answer: false,
          rationale: 'No. Contacts weld because they have been switching more current than they are rated for. Find out what caused that, usually a starting surge beyond the contact rating, or the new relay will weld in the same way.' },
        { kind: 'order', id: 'm9-lo4-q3', competency: 'Perform the procedure in servicing control boards and motor controllers.',
          stem: 'Arrange the steps for finding why a motor will not stop.',
          steps: [
            'Isolate the supply and lock it off',
            'Test the limit switch as it is operated',
            'Test the wiring from the switch to the controller',
            'Restore the control supply only and watch the controller input change state',
            'Check whether the relay coil is dropped out when the switch operates',
            'Isolate again, remove the relay and test its contacts',
          ] },
      ],
    },
    {
      id: 'lo5',
      title: 'Discuss sensors and actuators',
      lessons: [{
        id: 'l1',
        title: 'The two ends of every control system',
        blocks: [
          { kind: 'text', md: 'Every control system has the same two ends. A sensor turns something physical into an electrical signal so the controller can know about it. An actuator turns an electrical signal back into something physical so the controller can do something about it. Everything between them is decision.' },
          { kind: 'table',
            headers: ['Sensor', 'What it turns into a signal', 'How you test it'],
            rows: [
              ['Thermistor', 'Temperature, as a changing resistance', 'Measure resistance, then warm it and watch it change'],
              ['Limit switch', 'Position, as an open or closed contact', 'Continuity while it is operated by hand'],
              ['Light sensor', 'Light level, as a changing resistance', 'Measure resistance covered and uncovered'],
              ['Proximity sensor', 'Something nearby, as a switched output', 'Watch the output while a target is presented, with its supply connected'],
              ['Float switch', 'Liquid level, as an open or closed contact', 'Continuity while the float is lifted'],
            ] },
          { kind: 'table',
            headers: ['Actuator', 'What it does with a signal', 'How it fails'],
            rows: [
              ['Relay', 'Switches a larger current', 'Coil opens, or contacts weld'],
              ['Solenoid', 'Pulls a plunger a short distance', 'Coil opens, or the plunger jams'],
              ['Motor', 'Turns continuously', 'Winding opens, or bearings seize'],
              ['Valve', 'Opens or closes a flow', 'Coil opens, or debris holds it open'],
            ] },
          { kind: 'text', md: 'The important habit is testing a sensor by changing what it senses. A thermistor that reads a plausible resistance may still be dead, and the only way to know is to warm it and watch the reading move. A reading that does not respond is a failed sensor however sensible the number looks.' },
          { kind: 'note', md: 'A sensor reports and an actuator acts. When a machine misbehaves, decide which of the two is at fault before touching either, because the symptom looks the same from outside: a machine that is not doing the right thing.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo5-q1', competency: 'Discuss sensors and actuators.',
          stem: 'A thermistor measures 10 kilohms, which is a plausible value for it. Is it proven good?',
          options: [
            'Yes, the reading is within its normal range',
            'Yes, if the circuit also works',
            'No, because a dead sensor can sit at a plausible value and only change proves it works',
            'No, because thermistors always read zero when healthy',
          ],
          answer: 2,
          rationale: [
            'A plausible static reading is exactly what a failed sensor often gives.',
            'A working circuit says nothing about whether the sensor responds.',
            'Correct. Warm it and watch the resistance move. A reading that does not respond to the thing it senses is a failed sensor.',
            'A healthy thermistor reads a resistance that varies with temperature, not zero.',
          ] },
        { kind: 'mcq', id: 'm9-lo5-q2', competency: 'Discuss sensors and actuators.',
          stem: 'Which of these is an actuator?',
          options: [
            'A float switch',
            'A solenoid',
            'A thermistor',
            'A proximity sensor',
          ],
          answer: 1,
          rationale: [
            'A float switch reports a liquid level. That is a sensor.',
            'Correct. A solenoid takes an electrical signal and produces movement, which is what an actuator does.',
            'A thermistor reports temperature.',
            'A proximity sensor reports that something is near.',
          ] },
        { kind: 'truefalse', id: 'm9-lo5-q3', competency: 'Discuss sensors and actuators.',
          stem: 'A machine doing the wrong thing tells you whether the fault is in a sensor or an actuator.',
          answer: false,
          rationale: 'It does not. From outside, a sensor that reports wrongly and an actuator that acts wrongly look identical. Deciding which end is at fault is the first step, and it is done by checking whether the controller received the right information.' },
      ],
    },
    {
      id: 'lo6',
      title: 'Perform the procedure in servicing sensors and actuators',
      lessons: [{
        id: 'l1',
        title: 'Testing by changing what it senses',
        blocks: [
          { kind: 'safety', md: 'Isolate and lock off before working on any actuator, because a solenoid, valve or motor can operate the moment a signal changes and will not wait for your hand to move. Treat every actuator as though it is about to operate.' },
          { kind: 'text', md: 'A sensor is tested by changing what it senses and watching the signal move. A limit switch is operated by hand while you watch continuity. A thermistor is warmed while you watch resistance. A light sensor is covered while you watch its resistance rise. A static reading proves nothing on its own. Those three are passive, so they test with the supply still locked off. A proximity sensor is the exception, because it is an active device that produces no output at all without its own supply, so it is tested with that supply connected and the driven mechanism still isolated.' },
          { kind: 'text', md: 'An actuator is tested the other way round, by giving it the signal it expects and watching whether it acts. Apply the rated coil voltage to a relay off the machine and listen for the click. Energise a solenoid off the machine and feel the plunger pull. If it does not act on a correct signal, it has failed.' },
          { kind: 'steps', items: [
            'Isolate the supply and lock it off.',
            'Decide from the symptom whether the controller is being told the wrong thing or is failing to act.',
            'Test the sensor by changing what it senses and watching the reading move.',
            'Test the wiring between the sensor and the controller input.',
            'Test the actuator by applying its rated signal off the machine and watching it act.',
            'Refit, restore the supply, and confirm the machine does the right thing at every position.',
          ] },
          { kind: 'note', md: 'Testing an actuator off the machine matters. A solenoid that cannot move a jammed mechanism looks identical to a solenoid with an open coil until you take it out and give it a signal on the bench.' },
        ],
      }],
      quiz: [
        { kind: 'mcq', id: 'm9-lo6-q1', competency: 'Perform the procedure in servicing sensors and actuators.',
          stem: 'A solenoid does not move when the machine calls for it. You apply its rated voltage with the solenoid removed from the machine and the plunger pulls in strongly. What does that tell you?',
          options: [
            'The solenoid coil is open',
            'The solenoid is good, and the fault is either the signal reaching it or a jam in the mechanism',
            'The controller output has failed for certain',
            'The solenoid needs replacing anyway',
          ],
          answer: 1,
          rationale: [
            'An open coil would not pull in on the bench either.',
            'Correct. It acts correctly on a correct signal, so the fault is upstream of it or mechanical.',
            'The signal is one of two remaining possibilities, and you have not yet separated them.',
            'Replacing a part that has just been proven good wastes it and leaves the fault in place.',
          ] },
        { kind: 'truefalse', id: 'm9-lo6-q2', competency: 'Perform the procedure in servicing sensors and actuators.',
          stem: 'A limit switch that reads closed on a meter is proven working.',
          answer: false,
          rationale: 'Not until you operate it. A switch stuck closed reads closed, and so does a healthy one at rest. What proves it is watching the reading change as the switch is operated.' },
        { kind: 'order', id: 'm9-lo6-q3', competency: 'Perform the procedure in servicing sensors and actuators.',
          stem: 'Arrange the steps for servicing a sensor and actuator pair.',
          steps: [
            'Isolate the supply and lock it off',
            'Decide whether the controller is misinformed or failing to act',
            'Test the sensor by changing what it senses',
            'Test the wiring to the controller input',
            'Test the actuator off the machine with its rated signal',
            'Refit, restore the supply and confirm every position',
          ] },
      ],
    },
  ],
}
