// Writes the app icons as PNG bytes, with no dependency and no network.
//
// The spec forbids external assets, and an icon fetched or generated by a
// service at build time is exactly that. A PNG is a short header, one zlib
// stream of scanlines, and a CRC per chunk, so writing it directly is less
// work than adding an image toolchain that has to be installed on whatever
// machine builds this next.
//
// The mark is the one in the app header: a rounded plate-yellow square with a
// dark E, matching the Shadow Board's brass plate. Re-run with `npm run icons`
// after changing the accent in docs/DESIGN.md.
import { deflateSync } from 'node:zlib'
import { mkdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'public')

// docs/DESIGN.md, the Shadow Board plate. One plate colour for the whole app.
const PLATE = [0xf2, 0xc2, 0x30]
const GLYPH = [0x14, 0x18, 0x16]

const CRC_TABLE = (() => {
  const t = new Int32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    t[n] = c
  }
  return t
})()

function crc32(buf) {
  let c = -1
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8)
  return (c ^ -1) >>> 0
}

function chunk(type, data) {
  const len = Buffer.alloc(4)
  len.writeUInt32BE(data.length)
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data])
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(body))
  return Buffer.concat([len, body, crc])
}

/** RGBA pixel buffer to a PNG file buffer. */
function png(width, height, rgba) {
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr[8] = 8            // bit depth
  ihdr[9] = 6            // colour type: RGBA
  ihdr[10] = 0           // deflate
  ihdr[11] = 0           // adaptive filtering
  ihdr[12] = 0           // no interlace

  // Each scanline is prefixed with its filter type. Zero means "store the
  // bytes as they are", which costs a little size and keeps this readable.
  const raw = Buffer.alloc(height * (1 + width * 4))
  for (let y = 0; y < height; y++) {
    const at = y * (1 + width * 4)
    raw[at] = 0
    rgba.copy(raw, at + 1, y * width * 4, (y + 1) * width * 4)
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

/**
 * @param size      pixels square
 * @param fullBleed true for a maskable or Apple icon, where the launcher
 *                  applies its own shape and a transparent corner shows as a
 *                  black one. False for the ordinary icon, which supplies its
 *                  own rounded corners.
 */
function draw(size, fullBleed) {
  const rgba = Buffer.alloc(size * size * 4)
  const put = (x, y, [r, g, b], a = 255) => {
    const i = (y * size + x) * 4
    rgba[i] = r; rgba[i + 1] = g; rgba[i + 2] = b; rgba[i + 3] = a
  }

  const radius = fullBleed ? 0 : size * 0.22
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      let inside = true
      if (radius > 0) {
        const cx = x < radius ? radius : x > size - radius ? size - radius : x
        const cy = y < radius ? radius : y > size - radius ? size - radius : y
        inside = (x - cx) ** 2 + (y - cy) ** 2 <= radius ** 2
      }
      if (inside) put(x, y, PLATE)
    }
  }

  // A maskable icon's safe zone is the middle 80 percent, so the glyph sits
  // smaller on those. Everything is a fraction of the size, so every icon is
  // the same drawing.
  const inset = fullBleed ? 0.34 : 0.29
  const x0 = Math.round(size * inset)
  const x1 = Math.round(size * (1 - inset))
  const y0 = Math.round(size * (inset + 0.015))
  const y1 = Math.round(size * (1 - inset - 0.015))
  const t = Math.max(2, Math.round(size * 0.085))
  const mid = Math.round((y0 + y1) / 2 - t / 2)

  const bar = (bx0, by0, bx1, by1) => {
    for (let y = by0; y < by1; y++) {
      for (let x = bx0; x < bx1; x++) {
        if (x >= 0 && y >= 0 && x < size && y < size) put(x, y, GLYPH)
      }
    }
  }

  bar(x0, y0, x0 + t, y1)                                  // spine
  bar(x0, y0, x1, y0 + t)                                  // top arm
  bar(x0, mid, Math.round(x0 + (x1 - x0) * 0.78), mid + t) // middle arm
  bar(x0, y1 - t, x1, y1)                                  // bottom arm

  return png(size, size, rgba)
}

mkdirSync(OUT, { recursive: true })
const files = [
  ['icon-192.png', 192, false],
  ['icon-512.png', 512, false],
  ['icon-maskable-512.png', 512, true],
  ['apple-touch-icon.png', 180, true],
]
for (const [name, size, fullBleed] of files) {
  const bytes = draw(size, fullBleed)
  writeFileSync(join(OUT, name), bytes)
  console.log(`${name}  ${size}x${size}  ${bytes.length} bytes`)
}

/**
 * The Android app's launcher icons, for the APK students install offline.
 *
 * Kept apart from `draw` so the website's icons, which tests/icons.test.ts
 * decodes pixel by pixel, stay byte for byte what they were.
 *
 * Android wants three kinds, at five densities each:
 * - `ic_launcher`, the plain icon older phones (Android 7.x) show as it is.
 *   The same rounded plate-yellow square the website uses.
 * - `ic_launcher_round`, for launchers that ask for a circle.
 * - `ic_launcher_foreground`, the dark E alone on a transparent 108dp
 *   canvas. Android 8 and later composite it over the plate background
 *   colour and cut the result to whatever shape that phone's launcher uses,
 *   so the glyph has to sit inside the 66dp circle every shape keeps. A
 *   square E fits inside that circle with an inset of about 0.28; 0.32
 *   leaves room.
 */
function drawAndroid(size, shape) {
  if (shape === 'square') return draw(size, false)

  const rgba = Buffer.alloc(size * size * 4)
  const put = (x, y, [r, g, b], a = 255) => {
    const i = (y * size + x) * 4
    rgba[i] = r; rgba[i + 1] = g; rgba[i + 2] = b; rgba[i + 3] = a
  }

  if (shape === 'round') {
    const c = (size - 1) / 2
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        if ((x - c) ** 2 + (y - c) ** 2 <= (size / 2) ** 2) put(x, y, PLATE)
      }
    }
  }

  const inset = shape === 'foreground' ? 0.32 : 0.31
  const x0 = Math.round(size * inset)
  const x1 = Math.round(size * (1 - inset))
  const y0 = Math.round(size * (inset + 0.015))
  const y1 = Math.round(size * (1 - inset - 0.015))
  const t = Math.max(2, Math.round(size * 0.075))
  const mid = Math.round((y0 + y1) / 2 - t / 2)
  const bar = (bx0, by0, bx1, by1) => {
    for (let y = by0; y < by1; y++) {
      for (let x = bx0; x < bx1; x++) put(x, y, GLYPH)
    }
  }
  bar(x0, y0, x0 + t, y1)
  bar(x0, y0, x1, y0 + t)
  bar(x0, mid, Math.round(x0 + (x1 - x0) * 0.78), mid + t)
  bar(x0, y1 - t, x1, y1)

  return png(size, size, rgba)
}

const RES = join(dirname(fileURLToPath(import.meta.url)), '..', 'android', 'app', 'src', 'main', 'res')
const DENSITIES = [['mdpi', 48], ['hdpi', 72], ['xhdpi', 96], ['xxhdpi', 144], ['xxxhdpi', 192]]
try {
  statSync(RES)
  for (const [density, px] of DENSITIES) {
    const dir = join(RES, `mipmap-${density}`)
    writeFileSync(join(dir, 'ic_launcher.png'), drawAndroid(px, 'square'))
    writeFileSync(join(dir, 'ic_launcher_round.png'), drawAndroid(px, 'round'))
    // The adaptive foreground canvas is 108dp against the legacy icon's 48dp.
    writeFileSync(join(dir, 'ic_launcher_foreground.png'), drawAndroid(Math.round(px * 108 / 48), 'foreground'))
  }
  // The colour Android 8 and later draws behind the foreground.
  writeFileSync(join(RES, 'values', 'ic_launcher_background.xml'),
    `<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <color name="ic_launcher_background">#F2C230</color>\n</resources>\n`)
  console.log('android launcher icons written for 5 densities')
} catch {
  console.log('no android/ project here, skipping launcher icons')
}
